import type { Row } from './humanities';

// Individually authored, sequenced instruction. No generated title substitution.
// Each level builds on the preceding level; all examples are constructed cases.
export const philosophyContinuation: {title:string; rows:Row[]}[] = [
{title:'Formal reasoning: translating and testing arguments',rows:[
['Propositions and logical form',
'A proposition is something asserted that can be true or false. A sentence is its linguistic vehicle: two sentences can express the same proposition, and a question need not assert one. Propositional logic temporarily replaces whole propositions with letters so that connections become visible. The letter does not stand for a person or a single noun. Translation is a model of reasoning, not a replacement for interpreting what a speaker means.',
'Let P mean “the archive is open” and Q mean “the manuscript is accessible.” The argument “If P then Q; P; therefore Q” relates two complete claims. Replacing P with “archive” would lose the assertion that can be true or false. Before evaluating the argument, write the key for both letters.',
'What should the letter P represent in this translation?',
'The complete claim that the archive is open','The object called the archive',
'An object is not true or false. Supply a complete declarative claim for each letter, then translate the relations among those claims.'],
['Inclusive disjunction',
'In classical propositional logic, P or Q is inclusive: it is true when either is true and also when both are true. Everyday “or” can instead imply an exclusive choice. Do not silently import that implication. To express exactly one, add that P and Q are not both true. A truth table records each combination of truth values; it tests the formal connective, not whether a real-world event actually occurred.',
'A reading requirement says “submit a commentary or a translation.” Under inclusive or, submitting both satisfies it. Under exactly-one instructions, both violates it. The cases P true/Q false and P false/Q true satisfy either rule; P true/Q true is the case that distinguishes them.',
'Which case separates inclusive or from exactly one?',
'Both propositions being true','Only the first proposition being true',
'Both interpretations permit one true alternative. They disagree precisely on whether both alternatives may be true together.'],
['Material implication and its limits',
'The material conditional “if P then Q” is false only when P is true and Q is false. It therefore does not assert that P causes Q, or even that P occurs. A conditional with a false antecedent is true on this truth-functional account. This can sound unlike everyday promises or causal claims: those often carry relevance, timing, and counterfactual commitments absent from the material conditional.',
'Formalize “If the seal is broken, the indicator is red.” A broken seal with a non-red indicator refutes that conditional. An intact seal with a red indicator does not: another mechanism might make it red. The formula alone says nothing about that mechanism.',
'Which observation falsifies the material conditional?',
'A broken seal and a non-red indicator','An intact seal and a red indicator',
'Test the promised combination: a true antecedent must not accompany a false consequent. The conditional does not say redness requires a broken seal.'],
['Modus ponens and affirming the consequent',
'Modus ponens is the valid pattern: if P then Q; P; therefore Q. Affirming the consequent instead says: if P then Q; Q; therefore P. It is invalid unless an additional premise rules out other ways for Q to be true. To demonstrate invalidity, construct a situation with true premises and a false conclusion rather than merely saying the conclusion seems unlikely.',
'If a file is encrypted, it is unreadable without the key. This file is unreadable. Concluding that it is encrypted overlooks corruption. A corrupted, unencrypted file makes both premises true and the conclusion false. The problem is the inference, even if this particular file later turns out to be encrypted.',
'What does the corrupted-file countermodel establish?',
'The conclusion is not guaranteed by those premises','The file cannot possibly be encrypted',
'A countermodel defeats necessity of the inference, not every possible truth of the conclusion. Other evidence could still establish encryption.'],
['Modus tollens and denying the antecedent',
'Modus tollens says: if P then Q; not Q; therefore not P. If P had held, Q would have followed, so the failure of Q excludes P. Denying the antecedent says: if P then Q; not P; therefore not Q. This fails because Q may have another sufficient condition. Keep the conditional premise open to criticism even when the inference from it is valid.',
'If a shape is a square, it has four sides. A triangle does not have four sides, so it is not a square: modus tollens. A non-square rectangle still has four sides, showing why “not square, therefore not four-sided” fails.',
'Which inference is licensed by the stated square conditional?',
'Not four-sided, therefore not a square','Not a square, therefore not four-sided',
'The consequent must follow from being square; its absence excludes a square. Absence of squareness does not exclude other four-sided figures.'],
['Negating conjunctions and disjunctions',
'De Morgan’s laws track what it takes for combined claims to fail. Not both P and Q means at least one is false: not P or not Q. Neither P nor Q means both are false: not P and not Q. These are different strengths. Negating a rule requires careful scope: put parentheses around what the negation covers before translating it.',
'“It is not the case that both witnesses signed” is compatible with one signature. “Neither witness signed” excludes even one. If Ada signed and Ben did not, the first assertion is true and the second false. That single case prevents treating the phrases as equivalent.',
'Does “not both witnesses signed” entail that neither signed?',
'No; one may have signed','Yes; it excludes every signature',
'Not-both excludes the joint success case only. To exclude each signature separately, negate each proposition and join them with and.'],
['Testing validity with countermodels',
'A truth-table validity test asks whether any assignment makes every premise true and the conclusion false. One such row proves invalidity. If no such row exists, the form is valid in classical propositional logic. Rows with false premises do not refute validity. This procedure checks preservation of truth; it does not establish that the premises describe the world.',
'Consider P or Q; not P; therefore Q. To make the conclusion false, set Q false. The first premise then needs P true, but the second needs P false. No assignment meets all requirements. Contrast P or Q; P; therefore not Q: setting both true is a countermodel.',
'Which row would refute an argument’s validity?',
'All premises true and conclusion false','A premise false and conclusion false',
'Validity promises truth of the conclusion only when all premises are true. A row outside that condition cannot violate the promise.'],
['Universal and existential quantifiers',
'Predicate logic looks inside propositions. A universal assertion says every member of a specified domain meets a condition; an existential assertion says at least one member does. In standard first-order logic, “all dragons fly” does not itself assert dragons exist. Always specify the domain and distinguish a property from a relationship, such as one person trusting another.',
'In a domain of library items, “all manuscripts are catalogued” means any item that is a manuscript is catalogued. “Some manuscript is catalogued” additionally requires a manuscript. A library with no manuscripts satisfies the universal conditional but not the existential claim.',
'What extra commitment does “some manuscript is catalogued” make?',
'That at least one manuscript exists in the domain','That every library item is a manuscript',
'An existential quantifier supplies at least one witness. It neither includes every item nor follows from a universal conditional with an empty subject class.'],
['Quantifier order and dependency',
'“Everyone trusts someone” permits a different trusted person for each individual. “Someone is trusted by everyone” requires a single witness who works for all. Exchanging every and some can therefore change a claim. Think in terms of dependency: in the first statement your choice of witness may depend on which individual you start with; in the second it cannot.',
'In a two-person domain, Ada trusts only Ben and Ben trusts only Ada. Everyone trusts someone. Nobody is trusted by everyone, because neither trusts themself. This relation satisfies the first statement while refuting the second; no claim about actual human psychology is needed.',
'Why does the two-person case refute the reversed inference?',
'It supplies individual witnesses but no shared witness','It shows nobody trusts anybody',
'Each person does trust someone. What fails is the stronger requirement that one and the same person receive trust from everyone in the domain.'],
['Negating quantified claims',
'The negation of “every F is G” is “some F is not G,” not “every F is not G.” The negation of “some F is G” is “no F is G.” Use this to formulate a precise objection: denying a universal needs a counterexample, while denying an existential requires excluding every candidate. Scope mistakes often turn a reasonable criticism into an unsupported opposite extreme.',
'Thesis: every permissible policy is popular. One permissible but unpopular policy would refute it. That refutation would not show that all permissible policies are unpopular. Conversely, refuting “a permissible policy is popular” requires showing there is no such case in the specified domain.',
'What exactly negates “every permissible policy is popular”?',
'At least one permissible policy is not popular','Every permissible policy is unpopular',
'The universal fails at a single exception. Write the existential counterclaim first, then specify what evidence would establish its witness.']
]},
{title:'Knowledge: luck, reasons and social inquiry',rows:[
['Gettier cases and epistemic luck',
'The traditional analysis of knowledge as justified true belief faces Gettier-style cases: justification and truth can coincide through an accident. The challenge is not that the believer lacks all reasons. It is that the route producing belief connects to the truth in the wrong way. Proposed repairs include reliability, safety, and restrictions on defeating evidence; none should be introduced as an uncontested final definition.',
'A reliable-looking clock stopped earlier, but you consult it at the moment its hands happen to show the correct time. Your belief is true and ordinarily supported by looking at a clock, yet its truth is accidental. A functioning clock would connect your reading to the changing time rather than coincidence.',
'What makes the stopped-clock belief an epistemic problem?',
'Its truth is accidental relative to the method used','It is false at the moment it is consulted',
'The case deliberately grants truth. Explain the defective connection between evidence and truth instead of dismissing it as a false belief.'],
['Rebutting and undercutting defeaters',
'A defeater is information that weakens justification. A rebutting defeater supports the opposite conclusion; an undercutting defeater attacks the evidential connection without necessarily supporting the opposite. This distinction changes the rational response. Losing a reason to believe P may warrant suspension rather than belief in not P. Check whether the new information concerns the claim or the source’s ability to support it.',
'A photograph seems to show a blue fabric. A trustworthy physical inspection reporting red is rebutting evidence. Learning that the camera applied an unknown color filter undercuts the photograph as evidence, but does not by itself establish red, green, or any particular color.',
'What does discovering an unknown color filter support by itself?',
'Reduced confidence in the photograph’s color evidence','Certainty that the fabric is red',
'The source-to-claim link is compromised. Without independent color evidence, suspend or reduce confidence rather than selecting a specific opposite conclusion.'],
['Internalism and externalism about justification',
'Epistemic internalists emphasize factors accessible from the believer’s perspective; externalists allow justification or warrant to depend on factors such as actual reliability that the believer need not identify. There are multiple versions of each position. The dispute is not whether reasons ever matter, but whether accessible reasons exhaust what makes a belief epistemically good.',
'Two people have indistinguishable visual experiences, but one sees normally while the other is systematically deceived. An access-focused view can assign similar internal justification. A reliability-focused view can distinguish the processes’ connection to truth. Their disagreement concerns the standard, not the stipulated experiences.',
'Which feature can an externalist treat as relevant beyond accessible experience?',
'The process’s actual connection to truth','Only how convincing the experience feels',
'Externalism permits facts outside reflective access to matter. Convincingness is part of the shared perspective and cannot distinguish these stipulated cases.'],
['Reliabilism and the generality problem',
'Reliabilism connects justified belief with truth-conducive belief-forming processes. It must specify a process type: “vision,” “vision in dim light,” and “this single observation” can have different reliability profiles. The generality problem asks which type is epistemically relevant without choosing it merely to obtain a preferred verdict. A process that happened to be correct once is not thereby generally reliable.',
'A reader identifies a label in fog. Classifying the event as ordinary reading may rate it highly; classifying it as reading faint labels in fog may not. Describing it as “the process that produced this correct answer” trivially guarantees success and avoids the real evaluation.',
'Why is the one-off correct-answer classification inadequate?',
'It chooses a process description that guarantees the desired verdict','It proves all visual belief is unreliable',
'Choose a principled, relevant process type before assessing reliability. A local problem does not discredit every instance of perception.'],
['The regress of reasons',
'If every reason needs a further reason, justification appears to regress indefinitely. Foundationalism stops at basic justified beliefs; coherentism emphasizes mutual support within a system; infinitism permits an unending chain of reasons. These are families of theories, not merely three labels. Each owes an account of why its structure connects to truth rather than arbitrary assumption or internally consistent fiction.',
'Asked why you trust a document, you cite an archive; asked why you trust the archive, you cite records. Stopping at direct observation raises the question of why it is basic. Appealing to a network of mutually supporting records raises the question of independent contact with the world.',
'What challenge specifically faces a merely coherent fictional system?',
'Its mutual consistency may lack a connection to reality','Its beliefs cannot possibly support one another',
'Coherence can provide internal support. The objection asks whether that support alone distinguishes an elaborate fiction from a truth-connected system.'],
['Testimony and responsible reliance',
'Much knowledge depends on other people. Reductionist approaches seek support for testimony in independently established reliability; anti-reductionist approaches allow a defeasible entitlement to accept testimony without rebuilding every source’s credentials. Neither licenses credulity. Assess competence, sincerity, opportunity to know, and independence. Many repetitions of a single report do not equal many independent observations.',
'Three news summaries all cite the same unnamed witness. Their agreement may show faithful copying, not three confirmations. A separate observer with direct access adds a different evidential route. Source tracing matters even when all summaries are sincere and polished.',
'Why do the three summaries not supply three independent confirmations?',
'They inherit their factual basis from the same witness','Any secondhand claim is necessarily false',
'Testimony can transmit knowledge, but dependence limits corroboration. Trace where the information originated rather than counting websites or confident voices.'],
['Disagreement between epistemic peers',
'Epistemic peers are roughly equal in relevant evidence and competence for a question, not necessarily equal in every respect. Conciliationist views recommend reducing confidence after peer disagreement; steadfast views can sometimes permit maintaining it. A central difficulty is assessing peerhood without circularly treating agreement with you as proof of competence. Disagreement is higher-order evidence about your reasoning, not automatically a refutation.',
'Two careful readers inspect the same ambiguous sentence and reach opposite interpretations. Learning of the disagreement gives each reason to recheck scope and context. If one had missed a crucial paragraph, the evidential situation would no longer be symmetric.',
'Which discovery legitimately weakens the peer-disagreement symmetry?',
'One reader lacked a relevant paragraph','One reader disagrees with your conclusion',
'Unequal access to relevant evidence bears on peerhood independently of the verdict. Defining non-peers by disagreement simply assumes your own correctness.'],
['Epistemic injustice',
'Testimonial injustice occurs when identity prejudice unfairly reduces a speaker’s credibility. Hermeneutical injustice concerns unfair disadvantages in making experience intelligible through shared interpretive resources. These concepts distinguish a defect in credibility allocation from a gap in available understanding. Not every disagreement is an injustice: identify the prejudice or structural disadvantage and show its epistemic effect.',
'A competent witness is dismissed as irrational solely because of a stigmatized identity: a credibility deficit driven by prejudice. Separately, workers may lack a shared, institutionally recognized vocabulary to describe a recurring form of mistreatment, making reports difficult to articulate and understand.',
'What makes the witness case specifically testimonial injustice?',
'Prejudice lowers the credibility afforded to the speaker','The institution has too few words for the experience',
'The stipulated problem concerns whose testimony receives trust. Missing shared concepts instead foregrounds the hermeneutical dimension; cases can involve both.'],
['Contextualism and standards for knowledge',
'Epistemic contextualism holds that the truth conditions of knowledge attributions can vary with the attributor’s context. It is not the claim that reality changes when stakes rise. It differs from subject-sensitive views that place practical factors in the subject’s epistemic position. Compare who is speaking, which alternatives are relevant, and what evidence stays fixed before judging an example.',
'A person remembers a museum’s usual hours. A casual friend says “she knows it is open”; a speaker planning an irreplaceable visit demands ruling out a special closure. Contextualism locates a possible shift in the speakers’ standards for “knows,” not in whether the museum is actually open.',
'What is the contextualist proposed variable in this example?',
'The standards governing the speakers’ knowledge attributions','The museum’s physical opening status changing with conversation',
'Separate the proposition’s worldly truth from the context-sensitive standard for attributing knowledge of it. Higher conversational demands do not open or close a building.'],
['Design an epistemic audit',
'An epistemic audit traces a claim’s origin, inferential route, defeaters, and remaining uncertainty. Combine earlier tools: ask whether truth could be lucky, whether sources are independent, whether a challenge rebuts or undercuts, and whether disagreement exposes a missed premise. The output is a calibrated judgment with revision conditions, not a theatrical declaration that nothing can be known.',
'A historical claim appears in several articles that copy one memoir. The memoirist had access but wrote long afterward; an independent dated letter conflicts with part of the story. An audit separates dependence, memory limitations, and specific rebuttal, then narrows the claim rather than accepting or rejecting the entire memoir wholesale.',
'What is the strongest next move for the disputed historical detail?',
'Compare the independent letter with the memoir’s specific claim and provenance','Count the copied articles as independent votes',
'Independence and access matter more than repetition. State exactly which detail is challenged and what further evidence would change your judgment.']
]},
{title:'Philosophy of science: explanation and causal inference',rows:[
['Hume’s problem of induction',
'Induction projects patterns beyond observed cases. Hume’s challenge asks what justifies expecting unobserved nature to resemble observed nature. A deductive proof cannot exclude a change in pattern; citing past success of induction uses the very kind of reasoning under examination. The challenge concerns ultimate justification, not whether people can practically avoid all expectations or whether every prediction is equally reasonable.',
'An instrument behaved consistently in all past trials. “It will behave consistently because it always has” is a useful inductive expectation, but not a non-circular proof that induction must work. A prediction supported by controlled trials may remain better than a guess while still falling short of deductive certainty.',
'Why does past inductive success not provide a non-circular ultimate defense?',
'Projecting that success forward already uses induction','Past observations are logically impossible',
'The observations may be sound. The disputed step is the projection from their success to future reliability, which repeats the method being justified.'],
['Falsifiability and risky prediction',
'A falsifiable claim excludes possible observations. A risky prediction specifies an outcome a theory could genuinely fail to produce rather than accommodating everything afterward. Falsifiability is one proposed criterion for scientific status, not a guarantee of truth, value, or ethical acceptability. A false theory can be falsifiable; a useful metaphysical question may not be settled by an experiment.',
'“This mechanism always produces a visible signal under specified conditions” excludes a no-signal result in those conditions. “Whatever happens reflects the mechanism’s hidden intention” excludes nothing unless intention independently constrains outcomes. The first can fail; that exposure is a strength of the test, not proof it passes.',
'What gives the first claim empirical risk?',
'It identifies a possible observation that would conflict with it','It cannot ever turn out false',
'A testable theory risks conflict with observation. Immunity to every outcome removes that risk rather than establishing extraordinary confirmation.'],
['Auxiliary assumptions and theory testing',
'An experimental prediction typically follows from a theory together with auxiliary assumptions about apparatus, background conditions, and analysis. When the prediction fails, logic refutes the conjunction, not uniquely the central theory. This is associated with the Duhem–Quine problem. Avoid both extremes: treating one anomaly as automatic total refutation, or endlessly inventing untestable repairs to protect a theory.',
'A theory predicts a signal if the detector works and the sample is prepared correctly. No signal may implicate the theory, detector, or preparation. An independently calibrated detector and replicated preparation reduce the alternatives. Rechecking auxiliaries is legitimate when tests can expose their failure independently.',
'What does the missing signal logically refute first?',
'The combined package of theory and auxiliary assumptions','Only the central theory, irrespective of the apparatus',
'The prediction depends on the package. Independent checks help locate the failed assumption; logic alone does not isolate it from a single negative result.'],
['Underdetermination and model choice',
'Evidence underdetermines theory when competing accounts fit the available observations. This may be temporary or deeper; do not infer that all theories are equally good. Predictive reach, simplicity, coherence with independent findings, and new discriminating tests can matter. These virtues need argument: a simpler model may be easier to use without being a literally complete description of reality.',
'Two models fit the recorded motion of a system but disagree outside the measured range. Repeating the same narrow observations may add precision without separating them. Measuring in a feasible region of divergent prediction would be more discriminating, provided the instruments remain trustworthy there.',
'Which study best addresses this particular underdetermination?',
'Observe a region where the models make different predictions','Repeat only cases on which their predictions agree',
'Agreement cases can test shared predictions but cannot efficiently distinguish the alternatives. State the divergence before selecting the new observation.'],
['Scientific realism and instrumentalism',
'Scientific realists commonly hold that successful mature theories can give approximately true accounts of unobservable entities or structures. Instrumentalist approaches emphasize predictive utility without the same ontological commitment; constructive empiricism instead emphasizes empirical adequacy. Avoid lumping all non-realist positions together. Successful prediction is common ground; what success warrants believing beyond observation is disputed.',
'A model invoking an unseen mechanism predicts new observations. A realist may treat that success as evidence the mechanism approximately exists as described. A cautious empiricist may accept the model’s observable consequences while withholding belief about the unobservable mechanism. Neither need deny the observed predictive success.',
'What remains disputed after both parties accept the predictions?',
'Whether success warrants belief in the unobservable account','Whether the observed predictions succeeded at all',
'The example holds predictive success fixed. The philosophical disagreement concerns the additional inference from successful use to approximate truth about unobservables.'],
['Explanation versus prediction',
'Prediction concerns anticipating outcomes; explanation concerns why or how they occur. Some accounts of explanation emphasize laws, others mechanisms, unification, or counterfactual dependence. A variable can predict an outcome without explaining its production. Specify the question: explaining the timing, occurrence, or magnitude of an event may require different information.',
'A falling barometer can predict a storm, but smashing the barometer does not prevent it. Atmospheric conditions account for both the reading and weather change. The reading is an indicator rather than the storm-producing mechanism. A good predictor can therefore be a poor intervention target.',
'Why is breaking the barometer not an explanatory intervention on the storm?',
'The reading is an effect or indicator of conditions, not their cause','Any successful predictor must directly produce its outcome',
'Predictive association can arise from a common cause. Identify the producing process before treating a correlated indicator as a causal lever.'],
['Confounding and causal diagrams',
'A confounder helps explain an association because it influences both the proposed cause and the outcome. In a causal diagram, arrows encode causal assumptions, not facts automatically discovered in correlations. A path through a common cause can create association without the proposed direct effect. Adjustment requires substantive knowledge and an appropriate estimand; adding every available variable is not a universal solution.',
'Hot weather increases both ice-cream sales and swimming, while greater swimming exposure can increase drowning incidents. Ice-cream sales and incidents may therefore rise together without ice cream causing drowning. The common weather-related pathway supplies an alternative to the direct-cause story.',
'What should be investigated before claiming ice-cream sales cause drowning?',
'The shared weather and exposure pathway','Whether the two quantities can be mentioned in one sentence',
'An association does not identify its causal route. Articulate a plausible common cause and examine how exposure affects the observed relation.'],
['Randomization and its boundaries',
'Random assignment makes treatment allocation independent of participant characteristics in expectation, helping break confounding at baseline. It does not guarantee exact balance in a realized sample, prevent attrition, or establish applicability to every population. Random assignment differs from random sampling: the first supports causal comparison within a study; the second concerns how participants represent a population.',
'Volunteers are randomly assigned to two teaching methods. The assignment improves the comparison among volunteers. It does not make volunteers a random sample of all learners. If one method drives more struggling learners to drop out, comparing only final completers can introduce selection problems despite the initial randomization.',
'What does random assignment alone not establish?',
'That the volunteers represent all learners','That allocation was independent of participant characteristics in expectation',
'Assignment and sampling answer different questions. Also inspect follow-up and analysis, because a good starting allocation cannot repair every later selection problem.'],
['Selection and collider bias',
'A collider is a variable causally influenced by two other variables. Conditioning on it can create an association between its causes, even if they were otherwise independent. Selection into a dataset can perform that conditioning. This is why adjustment is not automatically safer: controlling a common effect differs from controlling a common cause. Draw arrow directions before deciding which variable to hold fixed.',
'Imagine a program admits applicants for exceptional research or exceptional performance. Among admitted students, someone with weaker research must often have stronger performance to qualify. A negative association can emerge within admissions even if the traits are independent in the applicant population. Admission is the common effect selected on.',
'Why can restricting attention to admitted students create a misleading association?',
'Admission is influenced by both traits and selection conditions on it','Admission necessarily causes the applicants’ original traits',
'The arrows run from traits to admission. Selecting their common effect changes the observed relationship without showing that one trait reduces the other.'],
['Preregistered tests and exploratory discovery',
'Preregistration records hypotheses and analysis decisions before the relevant outcomes are examined. It helps distinguish confirmatory testing from choices adapted to observed data; it does not guarantee a sound design or forbid exploration. Exploratory findings generate hypotheses whose evidential status should be labeled. A strong report separates what was planned, what changed, why, and what independent follow-up would test the new idea.',
'A researcher plans to test one outcome, finds little support, then discovers a striking subgroup pattern while exploring many divisions. The subgroup result may be worth investigating, but presenting it as the sole prior prediction hides the selection process. Reporting it as exploratory and testing it independently makes the reasoning inspectable.',
'How should the unplanned subgroup finding be presented?',
'As exploratory, with the search disclosed and independent testing proposed','As the only hypothesis predicted before seeing any outcomes',
'The finding is not worthless merely because it is unplanned. Its status changes because many outcome-informed choices can produce a selectively impressive pattern.']
]},
{title:'Normative ethics: principles, objections and public decisions',rows:[
['Act and rule consequentialism',
'Act consequentialism evaluates particular actions by their consequences; rule consequentialism evaluates actions through rules whose acceptance or practice has good consequences. The precise formulations differ. Rules may protect trust against tempting local exceptions, but a rule view must explain why it is not mere rule worship when breaking a rule appears beneficial. An act view must account for uncertainty and indirect effects rather than imagining perfect foresight.',
'A fabricated charitable report could attract donations now but damage trust when discovered. An act analysis must count those downstream risks. A rule analysis asks what happens under a practice permitting such fabrication, not just whether this isolated deception seems profitable. Both can oppose the lie for differently structured reasons.',
'Which question is distinctive of the rule-based consequentialist approach?',
'What consequences follow from general acceptance of the relevant rule?','What makes consequences wholly irrelevant to ethics?',
'Rule consequentialism remains consequence-based. It shifts the primary evaluation toward rules or their acceptance rather than abandoning outcome considerations.'],
['Kantian universalization and maxims',
'A maxim states an agent’s policy: in these circumstances, I will do this for this end. Kantian universalization asks whether the maxim can be willed as universal law, not merely whether many people dislike the act. Formulating the maxim fairly matters: adding a personal name to manufacture a convenient exception dodges the test. Different formulations and interpretations can lead to substantive debate.',
'Consider obtaining money by promising repayment while intending never to repay. If false promises became the accepted policy whenever money was wanted, the reliance that makes promising useful would be undermined. The criticism targets exploiting a practice while adopting a maxim incompatible with its universal operation.',
'Why is “only I may make false promises” not an adequate defense?',
'It builds a personal exception into the maxim instead of justifying universal permission','It shows no one relies on promises under any circumstances',
'The test requires a principled policy, not a name-based exemption. Explain how the maxim relates to the practice it presupposes.'],
['Humanity as an end',
'Kant’s humanity formulation prohibits treating rational agents merely as means, not using another’s services at all. Cooperation routinely involves means: the question is whether agency and ends receive appropriate respect. Consent matters but must not be reduced to a checkbox; deception, coercion, and unavailable alternatives can undermine its significance. Different moral theories can agree on a verdict while explaining it differently.',
'A tutor openly offers lessons at an agreed fee: both parties pursue ends through cooperation. A tutor hides a material limitation to secure payment prevents the learner from making an informed choice. The learner becomes a tool of the tutor’s plan rather than a participant able to assess it.',
'What morally relevant difference separates the two tutoring cases?',
'Deception obstructs the learner’s informed agency','Any payment necessarily treats a person merely as a means',
'Mutually understood service is not automatically mere instrumentalization. Identify the obstruction to agency rather than treating all exchange as inherently disrespectful.'],
['Prima facie duties and moral conflict',
'In W. D. Ross’s pluralist approach, a prima facie duty is a genuine moral reason, such as fidelity or beneficence, that may be outweighed by competing duties. “Prima facie” here does not mean an illusory duty that disappears once examined. The all-things-considered duty requires contextual judgment; the view does not supply a simple numerical ranking for every conflict.',
'You promised a friend routine help but encounter someone needing urgent assistance. The emergency may outweigh fidelity to the appointment. The promise still supplies a reason to notify your friend, apologize, or rearrange help. That residual responsibility distinguishes overriding a duty from declaring it never mattered.',
'Why might an apology still be appropriate after justified emergency assistance?',
'The overridden promise retained moral significance','Helping in the emergency was necessarily wrong',
'An outweighed duty can leave reasons for repair. Justification of the final choice need not erase every competing claim on the agent.'],
['Double effect and intended means',
'The doctrine of double effect distinguishes intended harm, including harm used as a means, from harm foreseen as a side effect. Traditional formulations also require conditions concerning the act’s character, proportionality, and how the good effect is achieved. Merely saying “I meant well” is insufficient. Both the doctrine and particular applications are contested; description of intention must answer to the actual plan.',
'Compare warning residents before necessary demolition, while accepting unavoidable inconvenience, with deliberately frightening residents because fear is the chosen method of making them leave. In the second plan fear is instrumental, not merely foreseen. This establishes a means/side-effect distinction; it alone does not settle either action’s permissibility.',
'When is an effect part of the intended means in this comparison?',
'When producing it is the selected method for reaching the end','Whenever the agent can foresee any possibility of it',
'Foreknowledge is not identical to intention. Ask whether the plan works by producing the effect, then separately examine proportionality and alternatives.'],
['Doing, allowing and negative responsibility',
'Some ethical views distinguish causing harm from allowing it, while consequentialist objections ask why the distinction should dominate avoidable outcomes. Neither description settles a case on its own. Duties of care, prior involvement, capability, and costs of rescue can make allowing harm gravely wrong. Avoid confusing a conceptual distinction with an absolute permission to remain inactive.',
'A caretaker notices a hazard within the area they are responsible for and could safely remove it. Saying “I did not create it” identifies an omission rather than a harmful act, but leaves the role-based protective duty untouched. Compare an uninvolved stranger with no knowledge of the hazard: responsibility differs for additional reasons.',
'Why does “I did not create the hazard” fail to settle the caretaker’s responsibility?',
'Their knowledge and protective role can generate a duty to intervene','Omissions can never be distinguished from actions in any respect',
'The distinction can be intelligible without excusing the omission. Analyze the role, knowledge, capacity, and reasonable rescue demands instead of relying on a label.'],
['Moral luck and the control condition',
'The control condition says moral assessment should depend on what lies within an agent’s control. Moral luck arises when factors beyond control appear to affect moral judgment: outcomes, circumstances, or formative traits. The puzzle is not that consequences have no practical relevance. It asks whether blameworthiness, compensation, and emotional response should track them in the same way.',
'Two equally careless drivers behave identically, but only one encounters a pedestrian who is injured. Both were reckless; only one caused that injury. It is coherent to distinguish equal culpability for carelessness from unequal duties of compensation, while recognizing that ordinary blame often responds strongly to the outcome.',
'Which distinction helps analyze this case without ignoring the injury?',
'Culpability for the risk-taking versus responsibility for actual damage','Claiming the injured pedestrian’s loss is unreal',
'Separate the moral quality of the controlled conduct from obligations generated by its result. A control-based account still owes serious attention to victims.'],
['Contractualism and reasonable rejection',
'Scanlonian contractualism asks which principles no one could reasonably reject as a basis for informed, unforced general agreement. It is not a survey of actual consent, and rejection is not reasonable simply because someone dislikes a rule. Justification considers individuals’ complaints under competing principles. This can challenge aggregating many trivial benefits to outweigh a severe burden on one person.',
'A proposed institution imposes a severe, avoidable burden on one member for tiny conveniences to many others. A contractualist asks whether that member has a reasonable complaint against the principle compared with alternatives. Counting beneficiaries alone does not yet answer the person who bears the concentrated burden.',
'What must be examined beyond how many people benefit?',
'The strength of individuals’ complaints against the available principles','Only whether everyone happened to sign a form',
'Reasonable rejection is a normative test of justification, not a signature count. Compare burdens under alternatives rather than assuming majority convenience settles fairness.'],
['Reflective equilibrium',
'Reflective equilibrium seeks a considered fit among judgments about cases, general principles, and relevant background theories. Revision can move in any direction: intuitions can be biased, principles overbroad, or factual beliefs mistaken. Wide reflective equilibrium considers rival frameworks rather than merely polishing an initial view. Coherence is a method of disciplined revision, not a guarantee that a social consensus is morally correct.',
'You endorse equal treatment, then judge that accessible formats should differ by need. Rather than discarding either immediately, refine equality toward fair access and test that principle on resource constraints and other cases. Also ask whether your starting judgments reflect familiarity or prejudice, and examine a serious rival principle.',
'What prevents this method from simply protecting the first intuition?',
'Allowing case judgments, principles, and background beliefs all to be revised','Declaring initial intuitions immune to criticism',
'Equilibrium must be reached through reciprocal adjustment and consideration of alternatives. An unrevisable starting intuition blocks the critical work the method requires.'],
['Capstone: justify an accessible public service',
'A defensible public decision combines empirical uncertainty with explicit moral reasons. State the feasible alternatives, who bears each burden, and which ethical principle connects facts to a recommendation. Use consequentialist effects, duties, and reasonable-rejection objections as distinct tests rather than pretending they always converge. Conclude with a bounded recommendation and a concrete condition for revising it.',
'A library can expand standard materials or fund accessible formats. First distinguish demand evidence from assumptions. Next compare gains and exclusions, examine equal-access duties, and state the strongest complaint from people facing either shortage. A justified recommendation might prioritize a basic accessible collection while specifying a review of unmet demand; the example does not establish a universal budget formula.',
'Which final argument best integrates the preceding levels?',
'A feasible recommendation with explicit values, evidence limits, a serious objection, and a revision condition','A declaration that one favored theory automatically settles every resource conflict',
'Write your recommendation, identify its empirical and normative premises, then steelman an objection. Explain what evidence or unresolved burden would require changing the policy; completion is practice, not proof of ethical expertise.']
]}
];
