import type { Row } from './humanities';
export const russian: Row[] = [
['A familiar vowel','Start with one Cyrillic letter and one clear sound. The displayed letter resembles Latin A and represents an ah-like vowel; pronunciation changes with stress and context in words.','Open your mouth comfortably and sustain a short ah without turning it into the English letter-name ay. This first mapping helps separate a letter’s sound from an English name.','Which sound is the useful first approximation?','Ah as in a calm open vowel','The English letter-name ay','Use the sound rather than importing the English alphabet name.'],
['A lookalike consonant','Some Cyrillic letters resemble Latin letters but represent different sounds. Learn the sound mapping deliberately rather than guessing from the familiar shape.','The displayed character looks like an English B but represents a v sound. Touch upper teeth lightly to lower lip and let air vibrate, rather than closing both lips for b.','What sound does this character represent?','V','B','The visual lookalike is misleading; Cyrillic and Latin alphabets use this shape differently.'],
['Informal hello','Greetings encode social relationship as well as information. This short greeting is informal and useful among friends or peers; it is not the safest default for every formal introduction.','In a fictional meeting between friends, the displayed greeting opens the exchange naturally. With an unfamiliar official, choose a more formal greeting from the extended lessons.','Where is this greeting most naturally suited?','A friendly informal encounter','Every formal occasion without distinction','Register depends on relationship and setting, not only dictionary meaning.'],
['Introducing your name','The name formula literally organizes the idea as “they call me.” Learn it as a reusable phrase before analyzing every grammatical ending. Add your actual name after the phrase.','At a first meeting, say the displayed formula and pause briefly before your name. The phrase introduces identity rather than asking the other person a question.','What do you add after this phrase?','Your name','A price','The formula introduces what you are called, not the cost of an item.'],
['Thanking someone','A basic thank-you works across many ordinary encounters. Keep the stressed syllable audible and distinguish a polite social response from a claim of agreement.','A clerk hands over a receipt; you use the displayed phrase. You are acknowledging help, not necessarily agreeing with every statement the clerk made.','What does this phrase do in the example?','Express thanks','Ask where the station is','Its communicative function is gratitude, not a location question.'],
['A polite request marker','A polite marker can accompany a request and also respond to thanks in context. One phrase can serve more than one conversational function.','When asking for an item, the displayed word softens the request. After thanks, it can mean you are welcome; context selects the reading.','What helps choose between please and you are welcome?','The surrounding exchange','The spelling changing for each meaning','The same form can serve different conversational functions.'],
['Yes and confirmation','A short affirmative can confirm an answer, but intonation and context matter. Practice hearing a response within an exchange rather than treating isolated syllables as the whole conversation.','In a fictional exchange, a friend asks in English whether you are ready; you answer with the displayed Russian word. It confirms readiness.','What does this response indicate here?','Yes','No','The displayed affirmative confirms the question in this context.'],
['No and negation','The basic negative response can stand alone. A complete negative sentence needs additional structure, so learn the short response without assuming it can replace all forms of negation.','When offered something you do not want, the displayed word supplies a short no. A polite tone and a thank-you may make the refusal warmer.','What is the basic meaning of this response?','No','Maybe with certainty','This is a negative response, not a probability estimate.'],
['Asking where','A short location question can omit an equivalent of present-tense “is.” Recognize the question pattern as a whole and listen for the stress on the place word.','You are looking for the metro entrance. The displayed question asks where it is, not whether you own it or where you went yesterday.','What information does this question request?','The location of the metro','The time of yesterday’s trip','The question word asks location, not past time.'],
['Repairing comprehension','A useful learner can signal non-understanding rather than pretending to follow. Learn this repair phrase early so conversation can slow down or change form.','A speaker gives directions too quickly. Use the displayed phrase, then ask for repetition from the next level. Repair supports communication rather than ending it.','What does this phrase communicate?','I do not understand','I disagree with your opinion','Lack of understanding differs from disagreement with the content.'],
['Ask for repetition','A polite plural or formal imperative is a useful default with unfamiliar adults. This phrase requests the same information again rather than a new topic.','After an unclear announcement, the displayed request asks someone to repeat. The polite marker keeps the request courteous without making it vague.','What response are you requesting?','A repetition of what was said','A change to an unrelated topic','Repeat requests repair the same message, not a new conversation.'],
['Ask for slower speech','This request changes speed while preserving the topic. It is especially useful with the previous repetition request; comprehension improves when you name what would help.','You recognize some words but cannot segment the stream. Ask for slower speech, then listen for the phrase boundaries rather than merely increasing volume.','What aspect should the speaker change?','Speaking speed','The subject to a completely different one','The phrase requests a slower pace, not different content.'],
['A present-tense identity','Russian often omits a present-tense equivalent of “am” in simple identity statements. The first-person pronoun plus a noun can form a complete ordinary statement.','The displayed sentence means I am a student, using a feminine student noun. It is not missing a word simply because English requires am.','What is understood without an explicit present-tense verb?','Am','Was yesterday','The simple identity statement is present, not automatically past.'],
['Expressing possession','A common possession construction is closer to “at me there is” than English “I have.” Learn the whole pattern before expecting word-for-word correspondence.','The displayed sentence says that you have a book. Its structure differs from English and Spanish, so translate the meaning rather than the word order.','What does the sentence communicate?','I have a book','I am a book','The construction expresses possession, not identity.'],
['Asking a price','A practical price question combines “how much” with a form meaning “costs.” It asks for an amount, not whether an item exists.','Point to an item and use the displayed question. After hearing the price, ask for repetition if needed rather than assuming a number you missed.','What answer should you expect?','A price','A person’s name','The question concerns cost rather than identity.'],
['Ordering water','A concise polite request can omit a verb in a clear service context. The noun form here marks the requested object; it is not the dictionary form in every construction.','At a café, the displayed phrase requests water politely. The situation supplies the understood action of bringing or giving it.','What does this request ask for?','Water','A train ticket','The object named in the phrase is water.'],
['Past action and gender','Russian past-tense singular forms commonly mark grammatical gender. The displayed sentence uses a feminine form for “read”; this is a grammatical feature, not a statement about intellectual ability.','A woman recounting yesterday’s reading can use this sentence. The final part of the verb reflects the feminine singular subject in this past-tense construction.','What time does this sentence refer to?','A past reading action','A command to read immediately','The verb is past tense, not an imperative.'],
['Future with an infinitive','One way to express future activity combines a future form of “be” with an imperfective infinitive. It foregrounds an activity rather than guaranteeing a completed result.','The displayed sentence says you will read. It does not by itself promise that an entire book will be finished.','What does this future expression emphasize?','Future reading activity','Guaranteed completion of an entire book','The construction does not specify a completed endpoint.'],
['A motion plan','Motion verbs distinguish ways and patterns of going. This useful first-person phrase expresses going somewhere on foot now or in a planned immediate direction, depending on context.','You leave a café and say the displayed sentence. It conveys going home on foot rather than a habitual journey by vehicle.','Which meaning best fits this phrase?','I am going home on foot','I always travel home by train','The verb and context indicate directed motion on foot.'],
['A reasoned preference','Combining a preference with a reason moves beyond isolated requests. Practice the relation between the clauses, keeping the explanation simple enough to say clearly.','The displayed sentence links liking reading with finding it interesting. The second clause gives a reason rather than an unrelated new statement.','What relation connects the clauses?','Preference and its reason','A question and a price','The connective introduces why the preference holds.'],
['Mild frustration versus literal food','Intensity 1/5: this word literally names a pancake but also serves as a mild euphemistic exclamation. It is informal, not core obscene mat; context determines whether food is intended.','Fictional dialogue: A says in English that they missed the bus. B uses the displayed exclamation. Here the reply means darn, not a request for pancakes.','What does the word mean in this bus exchange?','Darn, as a mild expression of frustration','An order for pancakes','The literal food sense is possible elsewhere; the frustrating event selects the interjection.'],
['A direct personal insult','Intensity 2/5: this is a common masculine noun meaning fool or idiot. It is insulting but not core obscene mat. Using it to address someone attacks the person rather than describing a disagreement.','Fictional scene: after an argument, one character calls another the displayed word. Compare “that decision was mistaken” in English: criticizing a decision is less personal.','What social action does direct address with this noun perform?','A personal insult','A neutral disagreement about evidence','Calling a person an idiot goes beyond disagreeing with a claim.'],
['A rude command to stop speaking','Intensity 3/5: this singular imperative means shut up. It is not core mat, but it is a direct rude command. The reflexive ending belongs to the verb; literal plugging imagery is not the normal translation.','Fictional dialogue: A interrupts repeatedly; B uses the displayed command. It silences rather than negotiates turns. A neutral request to let someone finish avoids the same aggression.','How should the command be translated in this dialogue?','Shut up','Please explain more','The imperative demands silence and is substantially rude.'],
['An abrupt dismissal','Intensity 3/5: the singular imperative here means get lost or leave me alone in colloquial use. Its literal verb history is not a useful word-for-word translation of the dismissal.','Fictional dialogue: A continues pestering after a refusal; B says the displayed word. The utterance demands distance and can escalate an argument; it is not a warm farewell.','What is the intended meaning here?','Get lost or leave me alone, rudely','Have a pleasant journey','The context is rejection, not a friendly travel wish.'],
['An elliptical send-off','Intensity 3/5: this masculine past-form construction can function as a dismissive command, roughly get lost. It is often an elliptical hostile send-off rather than a literal report of past walking.','Fictional dialogue: A makes a provoking remark; B uses the displayed phrase. Although its verb looks past, the utterance rejects A in the present interaction.','Why is a literal past-tense translation misleading here?','The construction functions as a dismissive command','All Russian past forms always mean commands','This is a particular idiomatic use, not a rule replacing ordinary past tense.'],
['An extremely obscene dismissal','Intensity 5/5: this phrase means fuck off or go fuck yourself. Its sexual literal imagery is not the intended action; it is a highly aggressive dismissal built with an imperative and an obscene noun.','Fictional dialogue: a conflict escalates and one character uses the displayed phrase to end contact. Recognizing it helps interpret severity; it is inappropriate in polite, professional or unfamiliar encounters.','What register does this dismissal carry?','Extremely obscene and hostile','Neutral everyday goodbye','The obscene noun makes it much stronger than a neutral request to leave.'],
['An obscene interjection','Intensity 5/5: used as an interjection, this word can mean fuck or for fuck’s sake. It also has a degrading noun sense referring to a person; do not automatically translate every exclamation as that noun.','Fictional scene: a character drops a phone and exclaims the displayed word at the situation. Here it expresses shock or frustration, not a literal accusation about a person.','Which distinction matters for interpreting the dropped-phone scene?','Interjection directed at the event versus a noun aimed at a person','The word is always a neutral technical term','Grammar and target affect meaning, but the interjection remains obscene.'],
['An obscene evaluation of disaster','Intensity 5/5: this noun is an obscene colloquial way to label a disastrous situation or emphatically say things are fucked. Tone can also convey shocked disbelief; it is not a neutral clinical description.','Fictional dialogue: A says the project files were lost. B uses the displayed exclamation. B evaluates the situation as a disaster rather than giving a technical account of the cause.','What does the reply primarily convey?','An obscene evaluation of a disastrous situation','A precise explanation of the software failure','The expression conveys stance and emotion, not a technical mechanism.'],
['Being intensely fed up','Intensity 5/5: this idiom means you have really fucking annoyed me or I am fucking fed up with you. The verb has sexual literal roots but commonly expresses exasperation here; the displayed past form addresses a male.','Fictional dialogue: a character repeats the same provocation and the other uses the displayed sentence. Interpret exasperation, not a literal claim about sex. The feminine past form would change the ending.','What is the idiomatic meaning in this exchange?','You have really fucking annoyed me','A literal statement that sex occurred','The common exasperation sense is distinct from the verb’s literal sexual senses.'],
['A firm non-obscene boundary','Intensity 1/5 for obscenity: this phrase means leave me alone. It remains firm and can sound sharp with angry intonation, but it avoids insults and core mat. Directness and obscenity are separate dimensions.','Fictional dialogue: A keeps arguing; B uses the displayed phrase and ends the exchange. Compare it with the obscene dismissal: both request separation, but this one avoids sexual profanity.','What distinguishes this boundary from the obscene dismissal?','It requests distance without obscene vocabulary','It cannot sound firm under any circumstances','A non-obscene phrase can still communicate a clear boundary.']
];
export const russianItems = [
['А','AH','the Cyrillic letter representing an ah-like vowel'],['В','VEH (letter name); V (sound)','the Cyrillic letter for the v sound'],['Привет','pree-VYET','hello (informal)'],['Меня зовут','mee-NYA za-VOOT','my name is / they call me'],['Спасибо','spa-SEE-ba','thank you'],['Пожалуйста','pa-ZHA-lu-sta','please / you are welcome'],['Да','DAH','yes'],['Нет','NYET','no'],['Где метро?','gdye mee-TRO','where is the metro?'],['Я не понимаю','ya nye pa-nee-MA-yu','I do not understand'],
['Повторите, пожалуйста','paf-ta-REE-tye pa-ZHA-lu-sta','repeat, please (formal/plural)'],['Говорите медленнее, пожалуйста','ga-va-REE-tye MYED-lyen-nye-ye pa-ZHA-lu-sta','speak more slowly, please'],['Я студентка','ya stu-DYENT-ka','I am a student (feminine)'],['У меня есть книга','u mee-NYA YEST KNEE-ga','I have a book'],['Сколько это стоит?','SKOL-ka EH-ta STO-eet','how much does this cost?'],['Воду, пожалуйста','VO-du pa-ZHA-lu-sta','water, please'],['Я читала','ya chee-TA-la','I read / was reading (past, feminine)'],['Я буду читать','ya BOO-du chee-TAT','I will read / be reading'],['Я иду домой','ya ee-DOO da-MOY','I am going home (on foot)'],['Я люблю читать, потому что это интересно','ya lyub-LYU chee-TAT pa-ta-MOO shta EH-ta een-tee-RYES-na','I like reading because it is interesting'],
['Блин!','BLEEN','darn! (mild); literally a pancake'],['Дурак','du-RAK','fool / idiot (masculine; insulting)'],['Заткнись!','zat-KNEES','shut up! (rude singular command)'],['Отвали!','at-va-LEE','get lost! / leave me alone! (rude)'],['Пошёл ты!','pa-SHOL TY','get lost! (dismissive; masculine form)'],['Иди на хуй!','ee-DEE NA KHUY','fuck off! / go fuck yourself! (extremely obscene)'],['Блядь!','BLYAT','fuck! / for fuck’s sake! (obscene interjection)'],['Пиздец!','peez-DYETS','it is fucked! / what a fucking disaster! (obscene)'],['Ты меня заебал!','ty mee-NYA za-ye-BAL','you have really fucking annoyed me! (to a male; obscene)'],['Оставь меня в покое','as-TAF mee-NYA f pa-KO-ye','leave me alone (firm, non-obscene)']
] as const;
