import Link from "next/link";
import { ProgramPath } from "@/components/Learning";

const levels = [
  { level: "I", title: "Foundation", detail: "Skin structure, a calm routine, labels, and barrier respect.", lessons: [["01", "Skin Is a Living Organ", "skin-as-an-organ"], ["02", "The Three-Step Routine", "build-a-basic-routine"], ["03", "Read a Product Label Like a Professional", "read-a-product-label"]] },
  { level: "II", title: "Barrier Care", detail: "Recognize irritation, support recovery, and use sun protection skillfully.", lessons: [["04", "Recognize an Overworked Barrier", "barrier-and-irritation"], ["05", "Sun Protection Is Treatment Prevention", "sunscreen-and-pigment"]] },
  { level: "III", title: "Concern Literacy", detail: "Acne, retinoid literacy, dark marks, and careful ingredient choices.", lessons: [["06", "Acne: Treat Gently and Consistently", "acne-basics"], ["07", "Retinoid and Retinol Literacy", "retinoid-literacy"], ["08", "Dark Marks and Uneven Tone", "dark-marks-and-tone"]] },
  { level: "IV", title: "Professional Practice", detail: "Sanitation, scope, referral judgment, and a complete routine audit.", lessons: [["09", "Sanitation and Scope", "sanitation-and-scope"], ["10", "Build Your Professional Routine Audit", "professional-routine-audit"]] },
] as const;

export default function SkincareStudyMapPage() {
  return <main className="subject-room-page skincare-room-page"><div className="subject-room-orbit" aria-hidden="true" /><header className="lesson-topbar"><Link href="/professorcitachka" className="back-link">← Professor’s Study</Link><span className="room-state">Department established</span></header><article className="subject-room-content"><div className="room-code skincare-room-code" aria-hidden="true">✧</div><p className="eyebrow">Professor Citachka · Department</p><h1>Skincare</h1><ProgramPath subject="skincare" /><p className="room-description">An esthetics-minded, evidence-aware course in skin care, ingredients, routines, sanitation, and professional judgment—from the first gentle cleanser to independent routine analysis.</p><blockquote>Beautiful skin care is not a race to use the strongest product. It is trained observation: know what the skin needs, protect what is working, and intervene with precision.</blockquote><section className="skincare-scope"><p className="eyebrow">Professional boundary</p><h2>Esthetics knowledge, medical discernment.</h2><p>This department teaches cosmetic care, hygiene, ingredient literacy, and routine design. It does not diagnose skin disease or replace dermatology. Painful, scarring, spreading, infected-looking, or rapidly changing concerns deserve medical evaluation.</p></section><section className="curriculum-ladder" aria-labelledby="skincare-levels"><p className="eyebrow">Your expanding pathway</p><h2 id="skincare-levels">Four levels of skincare mastery</h2>{levels.map((level) => <article className="curriculum-level" key={level.level}><span>Level {level.level}</span><div><h3>{level.title}</h3><p>{level.detail}</p><ol>{level.lessons.map(([number, title, slug]) => <li key={slug}><Link className="study-map-lesson-link" href={`/subjects/skincare/${slug}`}>Lesson {number}: {title}</Link></li>)}</ol></div></article>)}</section><Link className="primary-action" href="/subjects/skincare/skin-as-an-organ">Begin Level I: Skin Is a Living Organ →</Link></article></main>;
}
