"use client";

import Link from "next/link";
import {LegacyCompletion} from "@/components/LegacyCompletion";
import { useState } from "react";

type Lesson = { slug: string; number: number; unit: string; title: string; objective: string; plain: string; steps: readonly string[]; practice: string; question: string; choices: readonly string[]; correct: number; feedback: string; sources: readonly { label: string; url: string }[] };

export const skincareLessons: readonly Lesson[] = [
  { slug: "skin-as-an-organ", number: 1, unit: "Foundation", title: "Skin Is a Living Organ", objective: "Name skin's essential jobs before choosing products.", plain: "Skin is not a problem to scrub into submission. It is a living organ and a protective wall. Its outer layer helps keep water in and irritants out. A good routine supports this wall instead of constantly picking fights with it.", steps: ["Look at your routine and list every product that touches your face.", "Circle anything that stings, burns, or leaves you tight and raw.", "Choose one gentle product you can keep while learning what your skin tolerates."], practice: "Say the rule: “Protect first; treat second.” This prevents the common beginner mistake of using five harsh treatments at once.", question: "What is a core job of the outer skin barrier?", choices: ["Help keep water in and irritants out", "Remove every trace of oil", "Make all products work instantly"], correct: 0, feedback: "Correct. Esthetics begins with barrier respect, not aggressive product collecting.", sources: [{ label: "AAD: dermatologist-recommended skin care", url: "https://www.aad.org/public/everyday-care/skin-care-basics/care/skin-care-in-your-20s" }] },
  { slug: "build-a-basic-routine", number: 2, unit: "Foundation", title: "The Three-Step Routine", objective: "Build a simple morning and evening routine.", plain: "A routine needs a job for each step. Cleanser removes what needs removing. Moisturizer supports comfort and the barrier. Daytime sun protection reduces ultraviolet damage. More products are optional; these three jobs are the foundation.", steps: ["Morning: rinse or gently cleanse if needed.", "Apply moisturizer if your skin feels dry or tight.", "Finish with broad-spectrum SPF 30 or higher when you will be outdoors."], practice: "Write your exact morning routine in three lines. If a line has three products, it is not a line; it is a small civil war.", question: "Which order best fits a simple daytime routine?", choices: ["Cleanse, moisturize, sunscreen", "Sunscreen, scrub, cleanser", "Retinoid, exfoliant, no sunscreen"], correct: 0, feedback: "Correct. Keep the foundation simple before adding targeted treatments.", sources: [{ label: "AAD: daily cleanser and sun protection guidance", url: "https://www.aad.org/public/everyday-care/skin-care-basics/care/skin-care-in-your-20s" }, { label: "AAD: sunscreen FAQs", url: "https://www.aad.org/media/stats-sunscreen" }] },
  { slug: "read-a-product-label", number: 3, unit: "Foundation", title: "Read a Product Label Like a Professional", objective: "Separate a product's function from its marketing.", plain: "A label can tell you the product type, active ingredients, directions, warnings, and ingredient list. Marketing words are not a diagnosis. Start with the job: cleanse, moisturize, protect from sun, or treat a specific concern.", steps: ["Pick one product you own.", "Find its product type and directions.", "Find whether it lists an active ingredient or a Drug Facts panel."], practice: "Describe your product without using the word “glow.” State its job, directions, and one reason it may or may not suit your skin.", question: "What should you identify first on a product label?", choices: ["Its intended job and directions", "Its prettiest claim", "The influencer who recommended it"], correct: 0, feedback: "Correct. Professionals begin with function, instructions, and safety—not vibes alone.", sources: [{ label: "FDA: cosmetic products and ingredients", url: "https://www.fda.gov/cosmetics/cosmetic-products-ingredients" }] },
  { slug: "barrier-and-irritation", number: 4, unit: "Barrier Care", title: "Recognize an Overworked Barrier", objective: "Identify signs that a routine may be too irritating.", plain: "Irritation is not proof that something is “working.” Persistent burning, rawness, escalating redness, or peeling after new actives can mean your routine is too much. When the barrier is overwhelmed, simplify instead of adding another exfoliant.", steps: ["Pause newly added irritating products if your skin is reacting.", "Return to gentle cleansing, moisturizer, and sun protection.", "Introduce only one new product at a time after your skin is calm."], practice: "Make a “pause list”: write any product that burns or leaves your skin markedly more irritated. Do not stack it with another strong active to see who wins.", question: "What is the best first response to significant irritation from a new product?", choices: ["Simplify and stop the irritating product", "Add more acids immediately", "Scrub harder to remove it"], correct: 0, feedback: "Correct. Calm, simple care gives the barrier a chance to recover.", sources: [{ label: "AAD: overuse of exfoliation can damage the skin barrier", url: "https://www.aad.org/public/everyday-care/skin-care-basics/care/skin-care-in-your-20s" }] },
  { slug: "sunscreen-and-pigment", number: 5, unit: "Barrier Care", title: "Sun Protection Is Treatment Prevention", objective: "Choose basic sun protection criteria and explain why it matters.", plain: "Sunscreen is not only for beach days. Ultraviolet exposure contributes to sunburn, skin cancer risk, and premature aging; visible light can worsen darkening for some people. A practical choice is one you will use consistently that is broad-spectrum, SPF 30 or higher, and water resistant.", steps: ["Check whether your sunscreen says broad spectrum and SPF 30 or higher.", "Apply it as the final skincare step before makeup.", "Reapply as directed, especially after swimming or sweating."], practice: "Read your sunscreen label and record its SPF, whether it says broad spectrum, and whether it is water resistant.", question: "Which sunscreen description meets AAD's basic criteria?", choices: ["Broad-spectrum, SPF 30 or higher, water resistant", "Any moisturizer with a vague glow claim", "Only sunscreen used at the beach"], correct: 0, feedback: "Correct. Consistent sun protection is foundational esthetic care.", sources: [{ label: "AAD: sunscreen selection and use", url: "https://www.aad.org/media/stats-sunscreen" }] },
  { slug: "acne-basics", number: 6, unit: "Concern Literacy", title: "Acne: Treat Gently and Consistently", objective: "Understand a basic, non-prescription approach to mild acne.", plain: "Acne is not caused by being dirty. For mild acne, one targeted active used consistently can be more useful than a crowded shelf. Dermatologists discuss adapalene, azelaic acid, benzoyl peroxide, and salicylic acid for different acne patterns. Stronger is not automatically better; irritation can make care harder.", steps: ["Choose one concern you want to address rather than five.", "Use one new acne active as directed; do not layer several new ones at once.", "Keep moisturizer and sunscreen in the routine."], practice: "If you use an acne product, note its active ingredient and start date. Give a consistent routine time; acne products do not work overnight.", question: "What is a safer beginner approach to acne actives?", choices: ["Introduce one targeted active at a time", "Start every acne active on the same night", "Treat acne by harsh scrubbing"], correct: 0, feedback: "Correct. A controlled introduction lets you see what helps and what irritates.", sources: [{ label: "AAD: adult acne treatments and realistic timelines", url: "https://www.aad.org/public/diseases/acne/diy/adult-acne-treatment" }] },
  { slug: "retinoid-literacy", number: 7, unit: "Concern Literacy", title: "Retinoid and Retinol Literacy", objective: "Understand cautious, evidence-aware retinoid use.", plain: "Retinoids are vitamin-A-based products used for concerns such as acne, texture, fine lines, and uneven tone. They can irritate skin, so a cautious start and daily sun protection matter. Retinoids should not be used during pregnancy; redness, significant inflammation, allergies, or certain acne patterns deserve professional guidance.", steps: ["Do not start a retinoid during pregnancy.", "If appropriate for you, start low and infrequently rather than nightly.", "Use it at night, moisturize, and protect skin from sun during the day."], practice: "Before buying a retinoid, write one goal and one safety question for a dermatologist or pharmacist. A precise question is an esthetic skill.", question: "Which is a cautious retinoid practice?", choices: ["Start slowly and use sun protection", "Use more whenever skin peels", "Use during pregnancy without medical guidance"], correct: 0, feedback: "Correct. Retinoid success is usually gradual, supported, and unglamorous in the best way.", sources: [{ label: "AAD: retinoid and retinol guidance", url: "https://www.aad.org/public/everyday-care/skin-care-secrets/anti-aging/retinoid-retinol" }] },
  { slug: "dark-marks-and-tone", number: 8, unit: "Concern Literacy", title: "Dark Marks and Uneven Tone", objective: "Distinguish prevention from aggressive “brightening.”", plain: "Dark marks after acne or irritation are often driven by inflammation and can be worsened by more irritation or sun exposure. The first esthetic move is prevention: do not pick, protect from sun, and avoid making your skin angry in the name of faster results.", steps: ["Do not squeeze or pick active blemishes.", "Use consistent sun protection.", "Stop a product if it causes meaningful irritation or darkening."], practice: "Look at your routine and identify one behavior that prevents inflammation: gentler cleansing, no picking, or reliable sunscreen.", question: "What is a key way to help prevent post-inflammatory dark marks from worsening?", choices: ["Reduce irritation and use sun protection", "Add several harsh exfoliants", "Pick blemishes sooner"], correct: 0, feedback: "Correct. Inflammation management is often more useful than aggression.", sources: [{ label: "AAD: acne, dark marks, and dermatologist referral", url: "https://www.aad.org/public/diseases/acne/diy/adult-acne-treatment" }] },
  { slug: "sanitation-and-scope", number: 9, unit: "Professional Practice", title: "Sanitation and Scope", objective: "Know what an esthetic-minded routine can do—and when to refer.", plain: "Professional care means clean hands, clean tools, no sharing applicators, and knowing scope. Esthetic education can teach cosmetic care, ingredients, and supportive routines. It cannot diagnose a rash, treat a suspicious mole, or replace medical assessment.", steps: ["Wash hands before touching your face or products.", "Keep applicators and tools clean; do not share them.", "Refer painful, scarring, spreading, infected-looking, or changing concerns to a dermatologist."], practice: "Create a one-minute sanitation setup: clean hands, clean surface, clean applicator, product lids closed.", question: "Which concern is a reason to seek dermatology care rather than self-treat indefinitely?", choices: ["Painful or scarring acne that persists", "Wanting to learn cleanser order", "Choosing a lip balm texture"], correct: 0, feedback: "Correct. Referral is competent care, not failure.", sources: [{ label: "AAD: when acne needs dermatology care", url: "https://www.aad.org/public/diseases/acne/diy/adult-acne-treatment" }] },
  { slug: "professional-routine-audit", number: 10, unit: "Professional Practice", title: "Build Your Professional Routine Audit", objective: "Evaluate a routine for purpose, tolerance, and safety.", plain: "A strong routine is not a product haul. It is a small system: every product has a job, the skin tolerates it, sun protection is present, and the routine is adjusted calmly over time. This is how estheticians think: observe, simplify, introduce deliberately, and refer when needed.", steps: ["List products in morning and evening order.", "Write each product's job beside it.", "Remove duplicates or products that repeatedly irritate you; introduce replacements one at a time."], practice: "Complete your first audit: cleanser, moisturizer, sunscreen, targeted treatment, and any product whose job you cannot explain. That last category is homework, not shame.", question: "What makes a routine professionally coherent?", choices: ["Each product has a clear job and is tolerated", "The largest possible number of actives", "Changing everything every three days"], correct: 0, feedback: "Correct. Clear purpose, tolerance, consistency, and safety create a routine that can actually teach you something.", sources: [{ label: "AAD: build adjustable, consistent, tailored care", url: "https://www.aad.org/public/everyday-care/skin-care-basics/care/skin-care-in-your-20s" }] },
];

const progressKey = "professor-citachka:completed-lessons";
export function SkincareLesson({ slug }: { slug: string }) { return <SkincareLessonSession key={slug} slug={slug} />; }
function SkincareLessonSession({ slug }: { slug: string }) {
  const index = skincareLessons.findIndex((lesson) => lesson.slug === slug);
  const lesson = skincareLessons[index];
  const [selected, setSelected] = useState<number | null>(null);
  const [completed, setCompleted] = useState(false);
  if (!lesson) return null;
  const correct = selected === lesson.correct;
  const complete = () => { if (!correct) return; const stored = JSON.parse(localStorage.getItem(progressKey) ?? "[]"); const saved = Array.isArray(stored) ? stored.filter((item): item is string => typeof item === "string") : []; localStorage.setItem(progressKey, JSON.stringify(Array.from(new Set([...saved, `skincare/${lesson.slug}`])))); setCompleted(true); };
  return <main className="lesson-page skincare-lesson-page"><header className="lesson-topbar"><Link href="/subjects/skincare" className="back-link">← Skincare Study Map</Link><div className="lesson-progress" aria-label={`Skincare lesson ${index + 1} of ${skincareLessons.length}`}><span>{lesson.unit}</span><div><i style={{ width: `${((index + 1) / skincareLessons.length) * 100}%` }} /></div><strong>{String(index + 1).padStart(2, "0")} / {skincareLessons.length}</strong></div></header><article className="lesson-article"><header className="lesson-hero"><p className="eyebrow">Skincare · {lesson.unit} · Lesson {lesson.number}</p><h1>{lesson.title}</h1><p className="lesson-deck">{lesson.objective}</p></header><section className="music-core"><p className="eyebrow">Core idea</p><h2>Plain-language explanation</h2><p>{lesson.plain}</p></section><section className="music-steps"><p className="eyebrow">Do this now</p><h2>Three small steps</h2><ol>{lesson.steps.map((step) => <li key={step}>{step}</li>)}</ol></section><section className="music-practice"><p className="eyebrow">Practice</p><h2>Use the idea</h2><p>{lesson.practice}</p></section><section className="music-check" aria-label="Skincare lesson check"><p className="eyebrow">Quick check</p><h2>Show the idea is clear</h2><p>{lesson.question}</p><div className="music-choice-list">{lesson.choices.map((choice, choiceIndex) => <button key={choice} className={selected === choiceIndex ? "selected" : ""} onClick={() => setSelected(choiceIndex)} type="button">{choice}</button>)}</div>{selected !== null ? <p className={correct ? "answer-feedback correct" : "answer-feedback"} role="status">{correct ? lesson.feedback : "Not yet. Re-read the core idea and choose the safest, most evidence-aware answer."}</p> : null}</section><section className="skincare-sources"><p className="eyebrow">Lesson sources</p><ul>{lesson.sources.map((source) => <li key={source.url}><a href={source.url} target="_blank" rel="noreferrer">{source.label} ↗</a></li>)}</ul></section><footer className="lesson-finish"><Link href="/subjects/skincare" className="secondary-action">Return to Skincare Study Map</Link><LegacyCompletion lessonId={`skincare/${lesson.slug}`} model={lesson.feedback} eligible={correct} onComplete={complete} completed={completed} /></footer></article></main>;
}
