"use client";

import Link from "next/link";
import {LegacyCompletion} from "@/components/LegacyCompletion";
import { useState } from "react";
import {InstructionalVideo} from "@/components/InstructionalVideo";

type Track = "theory" | "guitar" | "keyboard" | "fl-studio";
type Lesson = {
  slug: string;
  track: Track;
  number: number;
  title: string;
  objective: string;
  plain: string;
  steps: readonly string[];
  practice: string;
  question: string;
  choices: readonly string[];
  correct: number;
  feedback: string;
  video?: { id: string; title: string; source: string };
};

export const musicLessons: readonly Lesson[] = [
  { slug: "beat-and-counting", track: "theory", number: 1, title: "The Beat: Music's Steady Footsteps", objective: "Find and count a steady beat in groups of four.", plain: "A beat is the steady pulse under music—the part you could clap or walk to. Think of four even footsteps: 1, 2, 3, 4. Keeping those footsteps even matters more than playing fast.", steps: ["Put one hand on your leg.", "Say: 1, 2, 3, 4 at an even speed.", "Tap once for every number. Do three groups without speeding up."], practice: "Make four quiet taps, then four more. Your only job is to keep the spaces between taps as even as you can.", question: "In beginner music, what is a beat?", choices: ["The steady pulse you can count or clap", "A fancy guitar trick", "A type of keyboard"], correct: 0, feedback: "Correct. Before chords and songs, your body learns the steady pulse." },
  { slug: "note-names-and-keyboard-map", track: "theory", number: 2, title: "Seven Letter Names", objective: "Name the repeating musical alphabet and find C.", plain: "Music uses seven letter names: A B C D E F G. Then the pattern starts again at A. On a keyboard, find a group of two black keys. The white key immediately to their left is C.", steps: ["Find any two black keys together.", "Touch the white key just to their left: that is C.", "Say the alphabet forward: A B C D E F G A."], practice: "Find three different C keys. They all have the same letter name, just higher or lower voices.", question: "Which white key is C?", choices: ["The key immediately left of two black keys", "The black key between two white keys", "The key immediately right of three black keys"], correct: 0, feedback: "Correct. The little group of two black keys is your reliable C signpost." },
  { slug: "scales-and-chords", track: "theory", number: 3, title: "Scales and Chords", objective: "Tell the difference between notes in a line and notes stacked together.", plain: "A scale is notes walking one after another, like steps up a staircase. A chord is notes sounding together, like friends standing side by side for a photograph. Both use the same musical alphabet.", steps: ["Play or sing C, then D, then E: that is a tiny scale.", "Play C and E together if you have a keyboard: that begins a chord sound.", "Listen for the difference: one-after-another versus together."], practice: "Say: “Scale means a line. Chord means together.” Then demonstrate each one with any two or three notes.", question: "Which description fits a chord?", choices: ["Notes played together", "Notes played one after another", "A metronome click"], correct: 0, feedback: "Correct. Chords are musical stacks; scales are musical paths." },
  { slug: "guitar-ready", track: "guitar", number: 4, title: "Meet Your Guitar Safely", objective: "Hold the guitar comfortably and make one clean note.", plain: "Your guitar should rest against you; your fretting hand should not have to hold its weight. The metal bars are frets. Place a fingertip just behind a fret—not on top of it—and use only enough pressure to make a clear sound.", steps: ["Sit tall and let the guitar body rest on your leg.", "Keep the neck steady with your strumming arm and body.", "Put one fingertip just behind a fret, pluck one string, then relax."], practice: "Make one clear note five times. If it buzzes, move closer to the metal fret; do not squeeze harder first.", question: "Where does a fretting finger go?", choices: ["Just behind the metal fret", "Directly on the metal fret", "Anywhere on the guitar body"], correct: 0, feedback: "Correct. Close behind the fret means clearer notes with less hand strain.", video: { id: "BBz-Jyr23M4", title: "Absolute beginner guitar: first chords and first song", source: "Andy Guitar" } },
  { slug: "guitar-first-chords", track: "guitar", number: 5, title: "Your First Two Chords", objective: "Build two simple chord shapes and change slowly between them.", plain: "A chord is a little finger shape that lets several strings speak together. Slow changes are not failure; they are the actual exercise. First make the shape carefully, then strum once, then reset.", steps: ["Choose one easy chord from the video, such as E minor.", "Place one finger at a time and pluck each string to check it.", "Lift your hand, rebuild, and repeat for three calm minutes."], practice: "Do not chase speed. Make five clean chord shapes in a row. Clean and slow is the correct beginning.", question: "What should you prioritize while learning a new chord?", choices: ["Clean finger placement", "Playing as fast as possible", "Pressing until your hand hurts"], correct: 0, feedback: "Correct. Speed comes from accurate, relaxed repetitions—not panic with a pick.", video: { id: "BBz-Jyr23M4", title: "Absolute beginner guitar: first chords and first song", source: "Andy Guitar" } },
  { slug: "guitar-rhythm-and-song", track: "guitar", number: 6, title: "Strum With the Count", objective: "Strum one chord on a steady four-count.", plain: "Rhythm is the promise that the beat will keep arriving. Start with one easy down-strum on count 1, then wait through 2, 3, 4. This is already real rhythm.", steps: ["Hold your easiest chord.", "Count 1, 2, 3, 4 aloud.", "Strum only on 1. Repeat eight times without stopping the count."], practice: "Play two bars: strum on 1, count to 4; then do it once more. A steady simple rhythm is better than a complicated wobbly one.", question: "If the music is in a four-count, how many beats do you count in one bar?", choices: ["Four", "Two", "Seven"], correct: 0, feedback: "Correct. Four beats make one basic bar in much popular music.", video: { id: "uBZsLmmOz9I", title: "Beginner guitar practice routine", source: "JustinGuitar" } },
  { slug: "keyboard-map-and-posture", track: "keyboard", number: 7, title: "Your MIDI Keyboard Map", objective: "Find C and play five neighboring notes with relaxed fingers.", plain: "A MIDI keyboard is a messenger: it tells the computer which key you pressed. The black-key pattern helps you find your place. Find two black keys; C is the white key immediately left of them.", steps: ["Find a pair of black keys.", "Find C directly to their left.", "With your right hand, play C D E F G using thumb through little finger."], practice: "Play C D E F G, then G F E D C. Keep your wrist loose, as if your hand is resting on a small ball.", question: "What does MIDI send to your computer?", choices: ["Information about notes and controls", "A physical piano sound by itself", "A guitar pick"], correct: 0, feedback: "Correct. MIDI carries musical instructions; the software chooses the sound.", video: { id: "r8G_0z-AzaY", title: "Piano keyboard layout and key names", source: "Lessons On The Web" } },
  { slug: "keyboard-first-melody", track: "keyboard", number: 8, title: "Play a Tiny Melody", objective: "Use one finger per key to play a five-note melody.", plain: "A melody is notes in a line that your ear remembers. We start with five nearby notes because your hand has five fingers. The goal is not a famous song; it is making each next note on purpose.", steps: ["Rest your right thumb on C.", "Give one finger to each key: C D E F G.", "Play C D E D C slowly, one note at a time."], practice: "Play C D E D C three times. If you miss a key, pause, find C again, and restart kindly.", question: "What is a melody?", choices: ["Notes played one after another", "All notes played at once", "A software menu"], correct: 0, feedback: "Correct. A melody is the musical sentence you can sing back." },
  { slug: "keyboard-chords-and-two-hands", track: "keyboard", number: 9, title: "One Hand Holds, One Hand Sings", objective: "Hold a simple chord while the other hand plays notes.", plain: "Your left hand can be the floor; your right hand can be the storyteller. Start by holding one low C with your left hand while your right hand plays C D E D C. Two hands do not need to be equally busy.", steps: ["Put your left little finger on a low C.", "Hold that key down gently.", "Play C D E D C above it with your right hand."], practice: "Hold the low C for one full four-count while your right hand plays the five-note melody once.", question: "What is a beginner-friendly first job for the left hand?", choices: ["Hold one steady low note", "Play every key at once", "Stay completely rigid"], correct: 0, feedback: "Correct. A stable bass note lets the other hand learn without chaos." },
  { slug: "fl-studio-tour", track: "fl-studio", number: 10, title: "FL Studio: Four Important Rooms", objective: "Recognize the Browser, Channel Rack, Playlist, and Mixer.", plain: "FL Studio can look like a spaceship at first. It is really a studio with rooms: Browser finds sounds; Channel Rack holds instruments and patterns; Playlist lays sections across time; Mixer controls volume and effects.", steps: ["Open FL Studio and look for the Browser.", "Find the Channel Rack and add one instrument.", "Find the Playlist and Mixer. Do not press every button; simply locate them."], practice: "Point to each room and say its job out loud. Naming the rooms makes the software less mysterious.", question: "Where do you arrange sections of your song across time?", choices: ["The Playlist", "The Browser", "The keyboard cable"], correct: 0, feedback: "Correct. The Playlist is your song timeline.", video: { id: "pDIsEZsalAo", title: "FL Studio complete beginner basics", source: "In The Mix" } },
  { slug: "fl-studio-first-beat", track: "fl-studio", number: 11, title: "Make a First Beat", objective: "Put a kick on four steady beats and play it as a loop.", plain: "A pattern is a small repeating musical tile. Put one kick drum on each of four beats. This gives you a floor to build on. One clean loop is a real beginning, not “nothing yet.”", steps: ["Choose a kick sound in the Browser.", "Place it on beats 1, 2, 3, and 4 in the Channel Rack.", "Press play and listen for four even thumps."], practice: "Make four even kick hits. Then add one clap on beat 2 and one clap on beat 4 if you want a next tiny step.", question: "What makes a basic four-on-the-floor kick pattern?", choices: ["A kick on each of four beats", "One kick at a random time", "No repeating pulse"], correct: 0, feedback: "Correct. Four even kick hits make a reliable rhythmic grid." },
  { slug: "fl-studio-midi-and-arrangement", track: "fl-studio", number: 12, title: "Put Your Melody Into a Song", objective: "Record or draw MIDI notes, then place a pattern in the Playlist.", plain: "MIDI notes are instructions, not sound waves. You can play them on your keyboard or draw them in Piano Roll. Once you have a small pattern, copy it into the Playlist to make a beginning, middle, and ending.", steps: ["Load a gentle instrument such as FLEX.", "Record or draw C D E D C in Piano Roll.", "Place the pattern in the Playlist three times, leaving space before the final repeat."], practice: "Make an eight-bar sketch: beat pattern, melody pattern, then a final quieter repeat. Save it with today’s date.", question: "What is MIDI in FL Studio?", choices: ["Editable note and control information", "A finished audio recording only", "A type of speaker"], correct: 0, feedback: "Correct. MIDI is editable musical information—excellent for learning, revising, and experimenting." },
];

const trackNames: Record<Track, string> = { theory: "Music Theory", guitar: "Guitar", keyboard: "MIDI Keyboard", "fl-studio": "FL Studio" };
const progressKey = "professor-citachka:completed-lessons";

export function MusicLesson({ slug }: { slug: string }) { return <MusicLessonSession key={slug} slug={slug} />; }
function MusicLessonSession({ slug }: { slug: string }) {
  const index = musicLessons.findIndex((lesson) => lesson.slug === slug);
  const lesson = musicLessons[index];
  const [selected, setSelected] = useState<number | null>(null);
  const [completed, setCompleted] = useState(false);
  if (!lesson) return null;
  const correct = selected === lesson.correct;
  const complete = () => {
    if (!correct) return;
    const stored = JSON.parse(localStorage.getItem(progressKey) ?? "[]");
    const items = Array.isArray(stored) ? stored.filter((item): item is string => typeof item === "string") : [];
    localStorage.setItem(progressKey, JSON.stringify(Array.from(new Set([...items, `music/${lesson.slug}`]))));
    setCompleted(true);
  };
  return <main className="lesson-page music-lesson-page"><header className="lesson-topbar"><Link href="/subjects/music" className="back-link">← Music Study Map</Link><div className="lesson-progress" aria-label={`Music lesson ${index + 1} of ${musicLessons.length}`}><span>{trackNames[lesson.track]}</span><div><i style={{ width: `${((index + 1) / musicLessons.length) * 100}%` }} /></div><strong>{String(index + 1).padStart(2, "0")} / {musicLessons.length}</strong></div></header><article className="lesson-article"><header className="lesson-hero"><p className="eyebrow">Music · {trackNames[lesson.track]} · Lesson {lesson.number}</p><h1>{lesson.title}</h1><p className="lesson-deck">{lesson.objective}</p></header><section className="music-core"><p className="eyebrow">One idea</p><h2>Plain-language explanation</h2><p>{lesson.plain}</p></section><section className="music-steps"><p className="eyebrow">Do this now</p><h2>Three tiny steps</h2><ol>{lesson.steps.map((step) => <li key={step}>{step}</li>)}</ol></section>{lesson.video ? <InstructionalVideo videoId={lesson.video.id}/> : null}<section className="music-practice"><p className="eyebrow">Two-minute practice</p><h2>Try it yourself</h2><p>{lesson.practice}</p></section><section className="music-check" aria-label="Lesson check"><p className="eyebrow">Quick check</p><h2>Show you have the idea</h2><p>{lesson.question}</p><div className="music-choice-list">{lesson.choices.map((choice, choiceIndex) => <button key={choice} className={selected === choiceIndex ? "selected" : ""} onClick={() => setSelected(choiceIndex)} type="button">{choice}</button>)}</div>{selected !== null ? <p className={correct ? "answer-feedback correct" : "answer-feedback"} role="status">{correct ? lesson.feedback : "Not yet. Return to the plain-language explanation, then try again. A clean foundation is worth the extra minute."}</p> : null}</section><footer className="lesson-finish"><Link href="/subjects/music" className="secondary-action">Return to Music Study Map</Link><LegacyCompletion lessonId={`music/${lesson.slug}`} model={lesson.feedback} eligible={correct} onComplete={complete} completed={completed} /></footer></article></main>;
}
