import Link from "next/link";
import { ProgramPath } from "@/components/Learning";
import { CurriculumHorizon } from "@/components/CurriculumHorizon";

const tracks = [
  { icon: "♫", title: "Music Theory", description: "Learn the map beneath every song: beat, note names, scales, and chords.", promise: "You will be able to count a beat, find notes, and understand why melodies and chords work.", lessons: [["01", "The Beat: Music's Steady Footsteps", "Find and count a steady beat in groups of four.", "beat-and-counting"], ["02", "Seven Letter Names", "Name the repeating musical alphabet and find C.", "note-names-and-keyboard-map"], ["03", "Scales and Chords", "Tell the difference between notes in a line and notes stacked together.", "scales-and-chords"]] },
  { icon: "♬", title: "Guitar", description: "Start with posture, clear notes, simple chords, and a steady strum.", promise: "Watch the close-up demos, then do tiny physical steps until your hands know what to do.", lessons: [["04", "Meet Your Guitar Safely", "Hold the guitar comfortably and make one clean note.", "guitar-ready"], ["05", "Your First Two Chords", "Build two simple chord shapes and change slowly between them.", "guitar-first-chords"], ["06", "Strum With the Count", "Strum one chord on a steady four-count.", "guitar-rhythm-and-song"]] },
  { icon: "♩", title: "MIDI Keyboard", description: "Use a MIDI keyboard to play notes, melodies, chords, and two-hand basics.", promise: "Your keyboard becomes both an instrument and a direct way to write ideas into FL Studio.", lessons: [["07", "Your MIDI Keyboard Map", "Find C and play five neighboring notes with relaxed fingers.", "keyboard-map-and-posture"], ["08", "Play a Tiny Melody", "Use one finger per key to play a five-note melody.", "keyboard-first-melody"], ["09", "One Hand Holds, One Hand Sings", "Hold a simple chord while the other hand plays notes.", "keyboard-chords-and-two-hands"]] },
  { icon: "✦", title: "FL Studio", description: "Turn beats, MIDI, and sound choices into a small finished project.", promise: "Learn the four essential workspaces before opening the rest of the spaceship.", lessons: [["10", "FL Studio: Four Important Rooms", "Recognize the Browser, Channel Rack, Playlist, and Mixer.", "fl-studio-tour"], ["11", "Make a First Beat", "Put a kick on four steady beats and play it as a loop.", "fl-studio-first-beat"], ["12", "Put Your Melody Into a Song", "Record or draw MIDI notes, then place a pattern in the Playlist.", "fl-studio-midi-and-arrangement"]] },
] as const;

export default function MusicStudyMapPage() {
  return <main className="subject-room-page music-room-page"><div className="subject-room-orbit" aria-hidden="true" /><header className="lesson-topbar"><Link href="/" className="back-link">← Professor’s Study</Link><span className="room-state">Department established</span></header><article className="subject-room-content"><div className="room-code music-room-code" aria-hidden="true">♫</div><p className="eyebrow">Professor Citachka · Department</p><h1>Music</h1><ProgramPath subject="music" /><p className="room-description">A beginner-first path from the first steady beat to playing guitar and MIDI keyboard, then using FL Studio to turn those skills into music.</p><blockquote>We do not begin by trying to be impressive. We begin by learning to hear, count, touch, and repeat—then the music has somewhere solid to stand.</blockquote><section className="music-orientation"><p className="eyebrow">Your first rule</p><h2>Small practice beats heroic confusion.</h2><p>On a busy day, do five minutes: count four beats, make one clean guitar chord or keyboard melody, and stop while you still know what you are doing. Consistent, accurate repetitions teach hands and ears far more reliably than an occasional exhausted marathon.</p></section><section className="music-track-grid" aria-label="Music study tracks">{tracks.map((track) => <article className="music-track" key={track.title}><span aria-hidden="true" className="music-track-icon">{track.icon}</span><p className="eyebrow">{track.lessons.length} foundation lessons</p><h2>{track.title}</h2><p>{track.description}</p><blockquote>{track.promise}</blockquote><ol>{track.lessons.map(([number, title, objective, slug]) => <li key={slug}><span>{number}</span><div><h3>{title}</h3><p>{objective}</p><Link className="study-map-lesson-link" href={`/subjects/music/${slug}`}>Start lesson {number}: {title}</Link></div></li>)}</ol></article>)}</section><CurriculumHorizon subject="music" /><Link className="primary-action" href="/subjects/music/beat-and-counting">Begin Music Lesson 1: The Beat →</Link></article></main>;
}
