import {afterEach,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen} from '@testing-library/react';
import {ReadAloudControls} from './ReadAloudControls';
vi.mock('next/navigation',()=>({usePathname:()=>'/learn/russian/01'}));
afterEach(()=>{cleanup();vi.unstubAllGlobals();});
function synth(voices:{lang:string;name:string}[]){const spoken:{text:string;lang:string;rate:number;onend?:()=>void}[]=[];class Utterance{text:string;lang='';rate=1;voice=null;onend?:()=>void;constructor(t:string){this.text=t;}}vi.stubGlobal('SpeechSynthesisUtterance',Utterance);const speech={cancel:vi.fn(),pause:vi.fn(),resume:vi.fn(),getVoices:()=>voices,speak:(u:typeof spoken[number])=>spoken.push(u),addEventListener:vi.fn(),removeEventListener:vi.fn()};Object.defineProperty(window,'speechSynthesis',{value:speech,configurable:true});return {speech,spoken};}
it('narrates teaching text with separate Russian language, excludes controls, supports speed and cancels on unmount',()=>{
 const {speech,spoken}=synth([{lang:'en-US',name:'English'},{lang:'ru-RU',name:'Russian'}]);const view=render(<><article id="teaching"><h1>A clear vowel</h1><p>Read <strong lang="ru">А</strong> as an open vowel.</p><p data-skip-read-aloud>Source https://example.com</p><fieldset><legend>Do not read the quiz</legend></fieldset><button>Do not read a control</button></article><ReadAloudControls targetId="teaching"/></>);
 fireEvent.click(screen.getByRole('button',{name:'Audio settings'}));fireEvent.change(screen.getByLabelText('Reading speed'),{target:{value:'0.8'}});fireEvent.click(screen.getByRole('button',{name:'Listen'}));expect(spoken.some(u=>u.lang==='ru-RU'&&u.text==='А')).toBe(true);expect(spoken.filter(u=>u.lang==='ru-RU').every(u=>!/[a-z]/i.test(u.text))).toBe(true);expect(spoken.map(u=>u.text).join(' ')).not.toMatch(/example.com|Do not read/);expect(spoken.every(u=>u.rate===0.8)).toBe(true);view.unmount();expect(speech.cancel).toHaveBeenCalled();
});
it('does not claim listening started with no matching voice',()=>{const {spoken}=synth([]);render(<><article id="copy"><p>Teaching content.</p></article><ReadAloudControls targetId="copy"/></>);fireEvent.click(screen.getByRole('button',{name:'Listen'}));expect(spoken).toHaveLength(0);expect(screen.getByRole('status')).toHaveTextContent(/voice/i);});
it('keeps the idle listener as a compact play button without an always-visible help block',()=>{synth([{lang:'en-US',name:'English'}]);render(<><main><nav className="lesson-topbar"/><article id="compact-copy"><p>Teaching content.</p></article></main><ReadAloudControls targetId="compact-copy"/></>);expect(screen.getByRole('button',{name:'Listen'})).toBeVisible();expect(screen.queryByText(/Device\/browser voice reading/)).not.toBeInTheDocument();expect(screen.queryByLabelText('Reading speed')).not.toBeInTheDocument();});
