import {programs,allTopics,requestedLevels,requestedUnits,topicHref} from '../src/lib/programs';
import {legacyPaths} from '../src/lib/legacy';
import {books} from '../src/app/subjects/literature/books';
import {courseUnits,courseAssessments,assessmentHref} from '../src/lib/assessments';
import {lessonDepth} from '../src/lib/lesson-depth';
import {lessonVisuals} from '../src/lib/lesson-visuals';
import {lessonVideoIds,instructionalVideos} from '../src/lib/instructional-videos';
import {mkdirSync,writeFileSync} from 'node:fs';
export function auditCurriculum(){
 const hasDepth=(p:typeof programs[number],t:ReturnType<typeof allTopics>[number])=>!!(t.depth||lessonDepth[`${p.id}/${t.id}`]);
 const depthOf=(p:typeof programs[number],t:ReturnType<typeof allTopics>[number])=>t.depth??lessonDepth[`${p.id}/${t.id}`];
 const subjects=programs.map(p=>({id:p.id,title:p.title,requestedUnits:requestedUnits(),publishedCoreUnits:courseUnits(p).filter(u=>!p.levels[u.levelIndex].supplemental).length,remainingRequestedUnits:requestedUnits()-courseUnits(p).filter(u=>!p.levels[u.levelIndex].supplemental).length,historicalRequestedLevels:requestedLevels(p.id),publishedMainLevels:p.levels.filter(l=>!l.supplemental).length,supplementalSequences:p.levels.filter(l=>l.supplemental).length,lessonCount:allTopics(p).length,units:courseUnits(p).map(u=>({id:u.id,title:u.title,level:u.levelIndex+1,lessonIds:u.topics.map(t=>t.id)})),assessments:courseAssessments(p).map(a=>{const fresh=a.questions.every(q=>q.reviewLessonIds);return {id:a.id,kind:a.kind,questions:a.questions.length,route:assessmentHref(p.id,a.id),freshApplicationBank:fresh,bank:fresh?'Separately authored application questions linked to review lessons.':'Existing individually authored lesson retrieval questions, grouped for unit and level review; not a new unseen examination bank.'};}),deeplyExpandedThisRevision:allTopics(p).filter(t=>hasDepth(p,t)).map(t=>({id:t.id,title:t.title,route:topicHref(p.id,t.id),addedWords:Object.values(depthOf(p,t)!).join(' ').split(/\s+/).length,readings:t.readings?.length??0,textStudySequence:!!t.visual})),notDeeplyExpandedThisRevision:allTopics(p).filter(t=>!hasDepth(p,t)).map(t=>t.id),lessonRoutes:allTopics(p).map(t=>topicHref(p.id,t.id)),extendedRoutes:(legacyPaths[p.id]??[]).map(slug=>`/subjects/${p.id}/${slug}`)}));
 const sum=(fn:(s:typeof subjects[number])=>number)=>subjects.reduce((n,s)=>n+fn(s),0);
 const report={generatedAt:new Date().toISOString(),scope:'Published inventory including one reviewed continuation level (two units, ten lessons) per course. The current target is 100 core units per course; remaining units are unpublished.',totals:{departments:subjects.length,requestedCoreUnits:sum(s=>s.requestedUnits),publishedCoreUnits:sum(s=>s.publishedCoreUnits),remainingRequestedCoreUnits:sum(s=>s.remainingRequestedUnits),historicalRequestedLevels:sum(s=>s.historicalRequestedLevels),publishedMainLevels:sum(s=>s.publishedMainLevels),freshApplicationAssessments:sum(s=>s.assessments.filter(a=>a.freshApplicationBank).length),lessonsWithCitedReadings:sum(s=>s.deeplyExpandedThisRevision.filter(t=>t.readings>0).length),textStudySequences:sum(s=>s.deeplyExpandedThisRevision.filter(t=>t.textStudySequence).length),supplementalSequences:sum(s=>s.supplementalSequences),publishedModernLessons:sum(s=>s.lessonCount),modernUnits:sum(s=>s.units.length),unitQuizzes:sum(s=>s.assessments.filter(a=>a.kind==='unit').length),cumulativeLevelTests:sum(s=>s.assessments.filter(a=>a.kind==='level').length),extendedLegacyLessons:sum(s=>s.extendedRoutes.length),literatureOpeningGuides:books.length,deeplyExpandedThisRevision:sum(s=>s.deeplyExpandedThisRevision.length),modernLessonsNotDeeplyExpandedThisRevision:sum(s=>s.notDeeplyExpandedThisRevision.length),newlyAuthoredDepthWords:sum(s=>s.deeplyExpandedThisRevision.reduce((n,t)=>n+t.addedWords,0))},subjects,guideRoutes:books.map(b=>`/subjects/literature#${b.id}`),limitations:['Each course now has one reviewed continuation level of two units and ten lessons; no course reaches the 100-unit target. Remaining units are unpublished.','Continuation lessons carry expanded explanations (600+ words), a second worked example, application tasks, cited readings and a text-based study sequence. Text study sequences are labeled steps, not drawn illustrations or videos.','Original lessons outside Russian 01-10 and Philosophy 01-10 keep their earlier, shorter explanations and are not counted as expanded.','Continuation-level unit quizzes and 12-question cumulative tests use separately authored application questions; earlier levels still reuse lesson retrieval questions.','Extended legacy sequences and the four book guides are not yet reorganized into their own units or given dedicated assessments.','Reading completion, study attendance and scored assessment attempts are separate. Migration creates no passing scores or historical dates. No AI or essay grading is claimed.','Browser-local storage only. Russian pronunciation uses available device voices; real audio and visual browser rendering have not been verified.']};
 const mediaEntries=[...programs.flatMap(p=>allTopics(p).map(t=>({key:`${p.id}/${t.id}`,route:topicHref(p.id,t.id)}))),...Object.entries(legacyPaths).flatMap(([subject,slugs])=>slugs.map(slug=>({key:`legacy:${subject}/${slug}`,route:`/subjects/${subject}/${slug}`}))),...books.map(b=>({key:`guide:${b.id}`,route:`/subjects/literature#${b.id}`}))].map(item=>({...item,newTopicIllustration:!!lessonVisuals[item.key],newControllableAnimation:!!lessonVisuals[item.key],videoId:lessonVideoIds[item.key]??null,videoMetadataAndProviderEmbedVerified:!!instructionalVideos[lessonVideoIds[item.key]],captionsVerified:false,playbackVerified:false}));
 const media={scope:'All published modern lessons, extended lessons and book guides; excludes decorative brand/art. Legacy repeated scene art is retained but not counted as newly authored topic-specific instruction.',totalLearningEntries:mediaEntries.length,originalTopicIllustrationsAdded:mediaEntries.filter(x=>x.newTopicIllustration).length,controllableAnimatedDiagramsAdded:mediaEntries.filter(x=>x.newControllableAnimation).length,lessonsWithMetadataVerifiedVideo:mediaEntries.filter(x=>x.videoMetadataAndProviderEmbedVerified).length,uniqueVerifiedVideoSources:new Set(mediaEntries.map(x=>x.videoId).filter(Boolean)).size,modernLessonsWithVideo:mediaEntries.filter(x=>!x.key.startsWith('legacy:')&&x.videoId).length,missingNewTopicSpecificIllustration:mediaEntries.filter(x=>!x.newTopicIllustration).map(x=>x.route),missingVideo:mediaEntries.filter(x=>!x.videoId).map(x=>x.route),limitations:'Four new original illustrations/animations only; not every lesson. Eight lessons map to four provider-embeddable videos, including five retained legacy music placements and three new modern placements. Exact title/creator/oEmbed checked; captions and actual playback unverified. Text and manual steps remain available. An animated diagram is not a video.',entries:mediaEntries};
 const completeReport={...report,media};
 mkdirSync('artifacts/pedagogy',{recursive:true});mkdirSync('public',{recursive:true});writeFileSync('artifacts/pedagogy/inventory.json',JSON.stringify(completeReport,null,2)+'\n');writeFileSync('public/curriculum-audit.json',JSON.stringify(completeReport,null,2)+'\n');return completeReport;
}
