export type RussianExample = {
  russian: string;
  latin: string;
  english: string;
  scene: string;
};

export type RussianLesson = {
  week: number;
  unit: number;
  slug: string;
  title: string;
  deck: string;
  objective: string;
  focus: string;
  examples: RussianExample[];
  checkPrompt: string;
  checkAnswer: string;
};

export const russianUnits = [
  { number: 1, title: "Foundations: sound, script, and first speech" },
  { number: 2, title: "Everyday life and description" },
  { number: 3, title: "Food, movement, and transactions" },
  { number: 4, title: "Past, future, and experience" },
  { number: 5, title: "Building independence" },
  { number: 6, title: "Consolidation and real use" },
] as const;

export const russianLessons: RussianLesson[] = [
  { week: 1, unit: 1, slug: "alphabet-foundations", title: "Alphabet Foundations", deck: "Six letters. Three words. One disciplined beginning.", objective: "Recognize, pronounce, and write six Cyrillic letters without guessing.", focus: "Read Cyrillic shapes as sounds, not as English look-alikes.", examples: [{ russian: "КОТ", latin: "koht", english: "male cat", scene: "a cat sitting under a moonlit window" }], checkPrompt: "Which Cyrillic letter makes the sound s?", checkAnswer: "С makes the s sound." },
  { week: 2, unit: 1, slug: "stress-and-sounds", title: "Stress and Sound", deck: "Hear the syllable that carries the word.", objective: "Notice stress and use it to pronounce common words clearly.", focus: "Russian stress can move; listen for the strongest syllable before speaking.", examples: [{ russian: "спаси́бо", latin: "spa-SEE-ba", english: "thank you", scene: "a traveler thanking a helpful station attendant" }], checkPrompt: "Where is the stress in спасибо?", checkAnswer: "The stress is on the second syllable: spa-SEE-ba." },
  { week: 3, unit: 1, slug: "greetings-and-courtesy", title: "Greetings and Courtesy", deck: "Open a conversation with warmth and precision.", objective: "Greet someone, say goodbye, and use basic polite responses.", focus: "Choose a greeting that fits the time and keep your first exchange short.", examples: [{ russian: "Здра́вствуйте", latin: "ZDRAST-vuy-tye", english: "hello (formal)", scene: "two neighbors greeting at an apartment entrance" }], checkPrompt: "What polite Russian greeting can you use with a stranger?", checkAnswer: "Здравствуйте is a formal, polite hello." },
  { week: 4, unit: 1, slug: "introductions-and-questions", title: "Introductions and Questions", deck: "Name yourself and invite a reply.", objective: "Introduce yourself and ask someone’s name.", focus: "Use меня зовут for your name and как вас зовут for a polite question.", examples: [{ russian: "Меня́ зову́т А́ня", latin: "mi-NYA za-VOOT AH-nya", english: "My name is Anya", scene: "Anya introducing herself at a language class" }], checkPrompt: "How do you politely ask, ‘What is your name?’", checkAnswer: "Как вас зовут?" },
  { week: 5, unit: 2, slug: "people-and-gender", title: "People and Gender", deck: "Describe who people are with simple nouns.", objective: "Identify common people words and notice grammatical gender.", focus: "Learn each noun with its natural ending instead of translating word by word.", examples: [{ russian: "Она́ студе́нтка", latin: "a-NAH stoo-DYENT-ka", english: "She is a student", scene: "a student carrying books into a university library" }], checkPrompt: "What does она mean?", checkAnswer: "Она means she." },
  { week: 6, unit: 2, slug: "family-and-possession", title: "Family and Possession", deck: "Talk about the people close to you.", objective: "Name family members and say whose something is.", focus: "Use мой and моя with the noun you are describing.", examples: [{ russian: "Э́то моя́ сестра́", latin: "EH-ta ma-YA sis-TRAH", english: "This is my sister", scene: "a girl introducing her sister in a family photo" }], checkPrompt: "Which word means ‘my’ with сестра?", checkAnswer: "Моя means my with сестра." },
  { week: 7, unit: 2, slug: "daily-routines", title: "Daily Routines", deck: "Put ordinary actions into the present tense.", objective: "Describe a simple daily routine using high-frequency verbs.", focus: "Russian present-tense endings change with the subject; practice complete short sentences.", examples: [{ russian: "Я рабо́таю до́ма", latin: "ya ra-BO-ta-yu DO-ma", english: "I work at home", scene: "a person working at a desk by a sunny window" }], checkPrompt: "How do you say ‘I work’ in the example?", checkAnswer: "Я работаю." },
  { week: 8, unit: 2, slug: "adjectives-and-places", title: "Adjectives and Places", deck: "Make a place vivid with one useful detail.", objective: "Use basic adjectives to describe familiar places.", focus: "Let an adjective agree with the noun while keeping the message simple.", examples: [{ russian: "Э́то большо́й парк", latin: "EH-ta bal-SHOY park", english: "This is a big park", scene: "families walking through a large green city park" }], checkPrompt: "What does большой mean?", checkAnswer: "Большой means big or large." },
  { week: 9, unit: 3, slug: "food-and-drink", title: "Food and Drink", deck: "Order something you can enjoy right away.", objective: "Name common food and drink items and make a basic order.", focus: "Use пожалуйста to make a request courteous.", examples: [{ russian: "Чай, пожа́луйста", latin: "chai, pa-ZHA-lus-ta", english: "Tea, please", scene: "a customer ordering tea at a cozy cafe" }], checkPrompt: "What polite word follows a simple order?", checkAnswer: "Пожалуйста means please." },
  { week: 10, unit: 3, slug: "shopping-and-prices", title: "Shopping and Prices", deck: "Ask what it costs before you buy.", objective: "Ask for a price and understand a short response.", focus: "Use сколько стоит to ask how much something costs.", examples: [{ russian: "Ско́лько э́то сто́ит?", latin: "SKOL-ka EH-ta STO-it", english: "How much does this cost?", scene: "a shopper checking the price of fruit at a market" }], checkPrompt: "How do you ask ‘How much does this cost?’", checkAnswer: "Сколько это стоит?" },
  { week: 11, unit: 3, slug: "transport-and-directions", title: "Transport and Directions", deck: "Move through a city with a clear destination.", objective: "Ask where transport goes and state a destination.", focus: "Use куда for ‘where to’ when movement is involved.", examples: [{ russian: "Куда́ идёт э́тот авто́бус?", latin: "koo-DAH i-DYOT EH-tat af-TO-bus", english: "Where does this bus go?", scene: "a passenger asking beside a city bus stop" }], checkPrompt: "Which question word asks ‘where to?’", checkAnswer: "Куда asks where to." },
  { week: 12, unit: 3, slug: "requests-and-help", title: "Requests and Help", deck: "Ask for help without losing your calm.", objective: "Make a practical request and explain that you need help.", focus: "Мне нужно gives you a reliable way to say what you need.", examples: [{ russian: "Мне ну́жна по́мощь", latin: "mnye noo-ZHNAH PO-mashch", english: "I need help", scene: "a traveler asking a librarian for assistance" }], checkPrompt: "What phrase means ‘I need help’?", checkAnswer: "Мне нужна помощь." },
  { week: 13, unit: 4, slug: "past-events", title: "Past Events", deck: "Say what happened yesterday.", objective: "Use a common past-tense form to report a completed action.", focus: "Past forms signal gender in the singular; practice the form you need.", examples: [{ russian: "Я была́ до́ма", latin: "ya by-LAH DO-ma", english: "I was at home", scene: "a woman relaxing at home after a rainy day" }], checkPrompt: "What does была mean in the example?", checkAnswer: "Была means was for a feminine speaker." },
  { week: 14, unit: 4, slug: "telling-a-short-story", title: "Telling a Short Story", deck: "Link two events and keep the sequence clear.", objective: "Tell a two-step story using then and a past action.", focus: "Start with a time marker, then add one event at a time.", examples: [{ russian: "Пото́м я пошла́ домо́й", latin: "pa-TOM ya pash-LAH da-MOY", english: "Then I went home", scene: "a woman walking home as evening lights appear" }], checkPrompt: "Which word means ‘then’?", checkAnswer: "Потом means then." },
  { week: 15, unit: 4, slug: "future-plans", title: "Future Plans", deck: "Make a plan for tomorrow.", objective: "Express a simple future plan with буду.", focus: "Буду plus an infinitive is a dependable future pattern.", examples: [{ russian: "Я бу́ду учи́ться", latin: "ya BOO-doo oo-CHEET-sa", english: "I will study", scene: "a learner planning a study session with a notebook" }], checkPrompt: "What word starts the future pattern in the example?", checkAnswer: "Буду starts the future pattern." },
  { week: 16, unit: 4, slug: "needs-and-preferences", title: "Needs and Preferences", deck: "State what you want and what you like.", objective: "Express a preference and a practical need in a short exchange.", focus: "Мне нравится literally centers the experience on ‘to me.’", examples: [{ russian: "Мне нра́вится му́зыка", latin: "mnye NRA-vit-sa MOO-zy-ka", english: "I like music", scene: "a listener enjoying music through headphones" }], checkPrompt: "How do you say ‘I like music’?", checkAnswer: "Мне нравится музыка." },
  { week: 17, unit: 5, slug: "weather-and-seasons", title: "Weather and Seasons", deck: "Describe the sky before you step outside.", objective: "Talk about basic weather and a seasonal condition.", focus: "Use сегодня to anchor a weather observation in today.", examples: [{ russian: "Сего́дня хо́лодно", latin: "si-VOD-nya HO-lad-na", english: "Today it is cold", scene: "a bundled pedestrian walking through a snowy street" }], checkPrompt: "What does холодно mean?", checkAnswer: "Холодно means it is cold." },
  { week: 18, unit: 5, slug: "comparisons-and-choices", title: "Comparisons and Choices", deck: "Choose between two useful options.", objective: "Make a simple comparison and state a preference.", focus: "Use лучше to say something is better.", examples: [{ russian: "Ме́тро лу́чше", latin: "me-TROO LOOT-she", english: "The metro is better", scene: "commuters choosing the metro over traffic" }], checkPrompt: "What does лучше mean?", checkAnswer: "Лучше means better." },
  { week: 19, unit: 5, slug: "advice-and-health", title: "Advice and Health", deck: "Offer a gentle suggestion when it matters.", objective: "Give one simple piece of advice and describe feeling unwell.", focus: "Тебе надо lets you make a practical recommendation.", examples: [{ russian: "Тебе́ на́до отдыха́ть", latin: "tye-BYE NA-da at-da-KHAT", english: "You need to rest", scene: "a friend suggesting rest with tea and a blanket" }], checkPrompt: "Which phrase gives advice in the example?", checkAnswer: "Тебе надо means you need to." },
  { week: 20, unit: 5, slug: "messages-and-arrangements", title: "Messages and Arrangements", deck: "Make a clear plan by text.", objective: "Set a meeting time and confirm an arrangement.", focus: "Use давай to propose a plan in an informal exchange.", examples: [{ russian: "Дава́й встре́тимся в семь", latin: "da-VAY VSTRYE-tim-sa v syem", english: "Let’s meet at seven", scene: "two friends arranging to meet outside a cinema" }], checkPrompt: "What word can introduce an informal suggestion?", checkAnswer: "Давай can introduce ‘let’s.’" },
  { week: 21, unit: 6, slug: "conversation-repair", title: "Conversation Repair", deck: "Keep the conversation going when you miss a word.", objective: "Ask someone to repeat or speak more slowly.", focus: "A repair phrase is a strength, not an apology.", examples: [{ russian: "Повтори́те, пожа́луйста", latin: "pav-ta-REE-tye, pa-ZHA-lus-ta", english: "Please repeat", scene: "a learner politely asking a teacher to repeat" }], checkPrompt: "How do you politely ask someone to repeat?", checkAnswer: "Повторите, пожалуйста." },
  { week: 22, unit: 6, slug: "home-and-neighborhood", title: "Home and Neighborhood", deck: "Describe where you live and what is nearby.", objective: "Talk about your home and name a nearby place.", focus: "Рядом means nearby and helps you orient a listener.", examples: [{ russian: "Ря́дом есть магази́н", latin: "RYA-dam yest ma-ga-ZEEN", english: "There is a shop nearby", scene: "a small neighborhood shop beside an apartment building" }], checkPrompt: "What does рядом mean?", checkAnswer: "Рядом means nearby." },
  { week: 23, unit: 6, slug: "integrated-conversations", title: "Integrated Conversations", deck: "Combine greetings, plans, and needs in one exchange.", objective: "Hold a short practical conversation using familiar building blocks.", focus: "Listen for the goal of the exchange before reaching for a grammar rule.", examples: [{ russian: "Я хочу́ зака́зать обе́д", latin: "ya kha-CHOO za-KA-zat a-BYED", english: "I want to order lunch", scene: "a customer speaking with a cafe server at lunchtime" }], checkPrompt: "What does хочу mean?", checkAnswer: "Хочу means I want." },
  { week: 24, unit: 6, slug: "a2-ready-review", title: "A2-Ready Review", deck: "Use the language you have built.", objective: "Review the pathway and respond to a familiar real-life prompt.", focus: "Choose clarity over complexity and repair meaning when needed.", examples: [{ russian: "Я немно́го говорю́ по-ру́сски", latin: "ya nyem-NO-ga ga-va-RYOO pa-ROOS-kee", english: "I speak a little Russian", scene: "a learner confidently speaking with a Russian neighbor" }], checkPrompt: "How do you say ‘I speak a little Russian’?", checkAnswer: "Я немного говорю по-русски." },
];

export function findRussianLesson(slug: string) {
  return russianLessons.find((lesson) => lesson.slug === slug);
}
